Repository hyperspy/hyperspy, pull requests merged in 2018-06, with the labels that each got.

#1967 User guide: fix typos and superfluous white space
  doc/user_guide/getting_started.rst
  doc/user_guide/intro.rst
  doc/user_guide/io.rst
  doc/user_guide/tools.rst
  doc/user_guide/visualisation.rst
Labels: affects: website, release: next patch, status: needs review, type: typo

#1962 User guide: remove (DRAFT) from the title
  doc/user_guide/index.rst
Labels: affects: documentation, affects: website, release: next patch, status: needs review

#1969 ADD note to UG, for users that cannot install dependencies from source
  doc/user_guide/install.rst
Labels: affects: documentation, status: waiting for author, type: proposal

#1977 Bug kramerskronig single spectrum
  hyperspy/_signals/dielectric_function.py
  hyperspy/_signals/eels.py
  hyperspy/misc/eels/tools.py
  hyperspy/tests/signal/test_kramers_kronig_transform.py
Labels: release: next patch, type: bug, type: bug-fix

#1970 Fix issue update marker
  hyperspy/_signals/eds.py
  hyperspy/drawing/figure.py
  hyperspy/drawing/marker.py
  hyperspy/drawing/signal1d.py
  hyperspy/signal.py
  hyperspy/tests/drawing/plot_markers/test_plot_eds_lines.png
  hyperspy/tests/drawing/test_plot_markers.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix, type: regression

#1981 BUGFIX reversed line order in animated legend in plot_spectra
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  setup.py
Labels: release: next patch, type: bug, type: bug-fix

#1963 Add support for loading specific dataset from EMD NCEM files
  doc/user_guide/io.rst
  hyperspy/io.py
  hyperspy/io_plugins/emd.py
  hyperspy/tests/io/test_emd.py
Labels: release: next minor, status: needs review, type: enhancement
