Repository hyperspy/hyperspy, pull requests merged in 2018-04, with the labels that each got.

#1648 Avoid spikes_removal_tool raising an error when ipywidgets_gui is not selected
  hyperspy/signal_tools.py
  hyperspy/ui_registry.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1830 Fix deprecation warning invalid escape sequence
  hyperspy/_components/lorentzian.py
  hyperspy/_components/volume_plasmon_drude.py
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/dielectric_function.py
  hyperspy/_signals/eels.py
  hyperspy/defaults_parser.py
  hyperspy/external/astroML/histtools.py
  hyperspy/external/mpfit/mpfitexpr.py
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/semper_unf.py
  hyperspy/misc/eels/tools.py
  hyperspy/misc/test_utils.py
  hyperspy/signal.py
  hyperspy/tests/__init__.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1875 Fix pytest parametrize deprecation warning.
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/tests/signal/test_map_method.py
Labels: release: next patch, status: needs review, type: bug-fix

#1896 Plot imaginary part of real numbers for ComplexSignal.
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/signal1d.py
Labels: release: next patch, status: waiting for author, type: bug-fix

#1890 Fix blit
  hyperspy/drawing/figure.py
  hyperspy/drawing/image.py
  hyperspy/drawing/marker.py
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/tiles.py
  hyperspy/drawing/widget.py
  hyperspy/misc/test_utils.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_signal1d.py
Labels: release: next patch, status: needs review, type: bug-fix

#1899 Fixes installation instructions for `hyperspy-gui-traitsui` in anaconda.
  doc/user_guide/install.rst
Labels: affects: documentation, affects: hyperspy_gui_traitsui, release: next patch, status: needs review, type: bug

#1901 Parse more metadata dm
  hyperspy/io_plugins/digital_micrograph.py
Labels: release: next patch, type: enhancement

#1888 New model plot kwargs
  doc/user_guide/model.rst
  hyperspy/models/model1d.py
  hyperspy/tests/drawing/plot_model1d/test_default_navigator_plot.png
  hyperspy/tests/drawing/plot_model1d/test_default_signal_plot.png
  hyperspy/tests/drawing/plot_model1d/test_disable_plot_components.png
  hyperspy/tests/drawing/plot_model1d/test_plot_components.png
  hyperspy/tests/drawing/test_plot_model1d.py
  setup.py
Labels: release: next minor, status: needs review, type: enhancement

#1852 Fix issue random failure async mrcz
  hyperspy/tests/io/test_mrcz.py
Labels: affects: tests, release: next minor

#1902 Fix default value of `rcond` in `numpy.linalg.lstsq` for numpy<1.14
  hyperspy/learn/onmf.py
Labels: release: next patch, type: bug, type: bug-fix

#1900 Fix redundant drawing connection
  hyperspy/drawing/image.py
  hyperspy/drawing/signal1d.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/signal_tools.py
Labels: release: next patch, type: bug, type: bug-fix

#1904 Use `get_children` to generate animated artists list when using blit
  hyperspy/drawing/figure.py
Labels: release: next patch

#1895 Fix lazy noise (#1886)
  hyperspy/signal.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next patch, status: needs review, type: bug-fix

#1907 Add missing folder to `package_data` in setup.py
  setup.py
Labels: release: next patch

#1905 Update mrcz version requirement to 0.3.6
  setup.py
Labels: release: next minor, type: bug, type: bug-fix

#1885 BUGFIX: Remove illegal filename characters from window titles
  hyperspy/drawing/utils.py
Labels: release: next patch, type: bug-fix

#1700 Fix dm reader when microscope info missing
  hyperspy/io_plugins/digital_micrograph.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1892 Fix exec permission
  INSTALL.txt
  doc/Makefile
  doc/_static/copybutton.js
  doc/conf.py
  doc/index.rst
  hyperspy/__init__.py
  hyperspy/_components/bleasdale.py
  hyperspy/_components/eels_cl_edge.py
  hyperspy/_components/eels_double_power_law.py
  hyperspy/_components/eels_vignetting.py
  hyperspy/_components/error_function.py
  hyperspy/_components/exponential.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/heaviside.py
  hyperspy/_components/logistic.py
  hyperspy/_components/lorentzian.py
  hyperspy/_components/offset.py
  hyperspy/_components/pes_core_line_shape.py
  hyperspy/_components/pes_see.py
  hyperspy/_components/power_law.py
  hyperspy/_components/rc.py
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/_components/voigt.py
  hyperspy/component.py
  hyperspy/components1d.py
  hyperspy/defaults_parser.py
  hyperspy/drawing/widgets.py
  hyperspy/external/mpfit/__init__.py
  hyperspy/io_plugins/README
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/image.py
  hyperspy/io_plugins/mrc.py
  hyperspy/io_plugins/netcdf.py
  hyperspy/misc/config_dir.py
  hyperspy/misc/ipython_tools.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/models/model2d.py
  hyperspy/tests/io/protochips_data/invalid_protochips_file.csv
  hyperspy/tests/io/protochips_data/protochips_electrical.csv
  hyperspy/tests/io/protochips_data/protochips_electrothermal.csv
  hyperspy/tests/io/protochips_data/protochips_thermal.csv
  hyperspy/tests/io/protochips_data/random_csv_file.csv
  hyperspy/tests/io/tiff_files/FEI-Helios-Ebeam-16bits.tif
  hyperspy/tests/io/tiff_files/FEI-Helios-Ebeam-8bits.tif
  hyperspy/tests/io/tiff_files/test_loading_image_saved_with_imageJ.tif
  hyperspy/tests/signal/__init__.py
  stdeb.cfg
Labels: release: next patch, status: needs review, type: bug-fix

#1903 Fix issue with parsing stage tilt angle values of emi files.
  hyperspy/io_plugins/fei.py
Labels: release: next patch, type: bug, type: bug-fix

#1699 Fix a few bugs with rectangle and span roi and other tweaks.
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/_widgets/rectangles.py
  hyperspy/drawing/widget.py
  hyperspy/tests/utils/test_roi.py
Labels: release: next patch, status: needs review, type: bug-fix

#1689 save(overwrite=False) now saves if no existing file
  hyperspy/io.py
  hyperspy/tests/io/test_io.py
Labels: release: next patch, status: needs review, type: bug-fix

#1879 Fourier log improve message
  hyperspy/_signals/signal1d.py
  hyperspy/tests/signal/test_1D_tools.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1909 Fix 1864 and add kwargs to GaussianHF's constructor
  hyperspy/_components/expression.py
  hyperspy/_components/gaussianhf.py
  hyperspy/tests/model/test_model_storing.py
Labels: release: next patch, status: needs review, type: bug-fix

#1913 Remove bundle build from appveyor (move to hyperspy-bundle repo)
  appveyor.yml
Labels: release: next patch, status: needs review

#1759 Fix progressbar showing when it shouldn't
  hyperspy/_signals/signal1d.py
  hyperspy/model.py
  hyperspy/signal_tools.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1914 Support all arguments of plot_images in case of single image.
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_colorbar_None.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_colorbar_multi.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_colorbar_single.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_saturated_pixels_5.0.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_saturated_pixels_saturated_pixels1.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_saturated_pixels_saturated_pixels2.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_saturated_pixels_saturated_pixels3.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next patch, type: bug-fix

#1915 Update user guide regarding traitsui supporting qt5
  doc/user_guide/install.rst
Labels: affects: documentation, affects: hyperspy_gui_traitsui

#1918 Fix lazy decomposition
  doc/user_guide/big_data.rst
  hyperspy/_signals/lazy.py
  hyperspy/learn/mva.py
  hyperspy/learn/rpca.py
  hyperspy/tests/mva/test_decomposition.py
  hyperspy/tests/mva/test_onmf.py
  hyperspy/tests/signal/test_folding.py
Labels: release: next patch, status: needs review, type: bug-fix

#1920 Move read scripts from web to UG
  doc/user_guide/io.rst
Labels: affects: documentation

#1921 Add link to bundle repo
  doc/user_guide/install.rst
Labels: affects: documentation, type: enhancement
