Repository hyperspy/hyperspy, pull requests merged in 2018-08, with the labels that each got.

#2024 Fix blit signal tool
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/signal1d.py
  hyperspy/signal_tools.py
Labels: release: next minor, type: bug, type: bug-fix

#2025 Fix numpy indexing deprecation warning. Add lazy test for tiff io.
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
Labels: affects: tests, release: next patch, type: enhancement

#2036 Fix eds set microscope parameters
  hyperspy/_signals/eds.py
  hyperspy/io_plugins/blockfile.py
  hyperspy/io_plugins/mrc.py
  hyperspy/io_plugins/msa.py
  hyperspy/io_plugins/netcdf.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/test_plot_markers.py
Labels: release: next patch, type: bug, type: bug-fix

#2037 Fix wrong baseline images for model plot testing: the "scatter" data …
  hyperspy/tests/drawing/plot_model/test_fit_EELS_convolved_False.png
  hyperspy/tests/drawing/plot_model/test_fit_EELS_convolved_True.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_False-False-False.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_False-False-True.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_False-True-False.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_False-True-True.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_True-False-False.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_True-False-True.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_True-True-False.png
  hyperspy/tests/drawing/plot_model/test_plot_gaussian_eelsmodel_True-True-True.png
  setup.py
Labels: affects: tests, release: next patch, status: waiting for author, type: bug, type: bug-fix

#2006 Add tests for #1994
  hyperspy/conftest.py
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal/test_plot_data_changed_event_1.png
  hyperspy/tests/drawing/plot_signal/test_plot_data_changed_event_2.png
  hyperspy/tests/drawing/test_plot_signal.py
Labels: release: next patch

#2038 Same as #2037 for RELEASE_next_minor branch
  hyperspy/tests/drawing/plot_model1d/test_default_signal_plot.png
  hyperspy/tests/drawing/plot_model1d/test_disable_plot_components.png
  hyperspy/tests/drawing/plot_model1d/test_plot_components.png
Labels: affects: tests, type: bug, type: bug-fix

#2040 Add indices control to documentation
  doc/conf.py
  doc/user_guide/getting_started.rst
  doc/user_guide/model.rst
Labels: affects: documentation, release: next patch, type: enhancement

#2003 plot remainder in remove_background
  doc/user_guide/signal1d.rst
  hyperspy/_signals/signal1d.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/plot_signal_tools/test_plot_BackgroundRemoval.png
  hyperspy/tests/drawing/test_plot_signal_tools.py
  hyperspy/tests/signal/test_remove_background.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2016 Add add_powerlaw argument to get_core_loss_eels_signal/model
  hyperspy/datasets/artificial_data.py
  hyperspy/tests/datasets/test_artificial_data.py
Labels: release: next minor, status: WIP, type: enhancement

#1290 Add sub-pixel accuracy to 2D alignment
  hyperspy/_signals/signal2d.py
  hyperspy/tests/signal/test_2D_tools.py
Labels: release: next minor, type: enhancement

#2042 Fix ReadTheDocs API docs
  .gitignore
  doc/api/hyperspy._components.rst
  doc/api/hyperspy._signals.rst
  doc/api/hyperspy.datasets.rst
  doc/api/hyperspy.docstrings.rst
  doc/api/hyperspy.drawing._markers.rst
  doc/api/hyperspy.drawing._widgets.rst
  doc/api/hyperspy.drawing.rst
  doc/api/hyperspy.external.astroML.rst
  doc/api/hyperspy.external.mpfit.rst
  doc/api/hyperspy.external.rst
  doc/api/hyperspy.io_plugins.rst
  doc/api/hyperspy.learn.rst
  doc/api/hyperspy.misc.eds.rst
  doc/api/hyperspy.misc.eels.rst
  doc/api/hyperspy.misc.holography.rst
  doc/api/hyperspy.misc.io.rst
  doc/api/hyperspy.misc.machine_learning.rst
  doc/api/hyperspy.misc.rst
  doc/api/hyperspy.models.rst
  doc/api/hyperspy.rst
  doc/api/hyperspy.samfire_utils.goodness_of_fit_tests.rst
  doc/api/hyperspy.samfire_utils.rst
  doc/api/hyperspy.samfire_utils.segmenters.rst
  doc/api/hyperspy.samfire_utils.weights.rst
  doc/api/hyperspy.tests.axes.rst
  doc/api/hyperspy.tests.component.rst
  doc/api/hyperspy.tests.datasets.rst
  doc/api/hyperspy.tests.drawing.rst
  doc/api/hyperspy.tests.io.rst
  doc/api/hyperspy.tests.misc.rst
  doc/api/hyperspy.tests.model.rst
  doc/api/hyperspy.tests.mva.rst
  doc/api/hyperspy.tests.rst
  doc/api/hyperspy.tests.samfire.rst
  doc/api/hyperspy.tests.signal.rst
  doc/api/hyperspy.tests.utils.rst
  doc/api/hyperspy.utils.rst
  doc/api/modules.rst
  doc/conf.py
  doc/generate_api_doc.sh
  doc/gh-pages.py
  doc/pip-req.txt
  doc/readthedocs.yml
  setup.py
Labels: affects: documentation, status: needs review, type: bug-fix

#1968 Bug iterate signal with markers
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_markers.py
Labels: status: fix-submitted, type: bug, type: bug-fix

#1727 Intensity log scale plot
  doc/user_guide/images/hologram_fft.png
  doc/user_guide/metadata_structure.rst
  doc/user_guide/tools.rst
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/complex_signal2d.py
  hyperspy/docstrings/plot.py
  hyperspy/drawing/image.py
  hyperspy/drawing/mpl_he.py
  hyperspy/drawing/mpl_hie.py
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/utils.py
  hyperspy/interactive.py
  hyperspy/roi.py
  hyperspy/signal.py
  hyperspy/tests/drawing/plot_signal/test_plot_data_changed_event_2.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_log_scale.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_FFT_False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_FFT_True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_False-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_False-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_True-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_True-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_ps_False-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_ps_False-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_ps_True-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_complex_ps_True-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_log_scale.png
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/signal/test_fourier_transform.py
Labels: release: next minor, status: needs review, type: New feature

#2032 Speed up fast background removal
  .travis.yml
  appveyor.yml
  hyperspy/_components/eels_double_power_law.py
  hyperspy/_components/expression.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussianhf.py
  hyperspy/_components/offset.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/power_law.py
  hyperspy/_signals/signal1d.py
  hyperspy/component.py
  hyperspy/docstrings/parameters.py
  hyperspy/signal_tools.py
  hyperspy/tests/component/test_component.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_components2D.py
  hyperspy/tests/component/test_gaussianhf.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signal/test_remove_background.py
  setup.py
Labels: release: next minor, status: needs review, type: bug-fix, type: enhancement

#2046 Fix error when reading dm4 files larger than 4Gb
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/misc/io/utils_readfile.py
Labels: release: next minor, status: needs review, type: bug-fix

#1910 New roi line angle
  doc/user_guide/images/roi_line2d_holo.png
  doc/user_guide/images/roi_line2d_rotate.png
  doc/user_guide/tools.rst
  hyperspy/roi.py
  hyperspy/tests/utils/test_roi.py
Labels: release: next minor, status: needs review, type: enhancement
