Repository hyperspy/hyperspy, pull requests merged in 2018-03, with the labels that each got.

#1867 Fix ScaleableFixedPattern missing arguments
  hyperspy/_components/scalable_fixed_pattern.py
Labels: release: next patch, type: bug-fix

#1793 ENH: add colormap iterating to plot_images
  doc/user_guide/images/plot_images_eds.png
  doc/user_guide/images/plot_images_eds_cmap_factors_side_by_side.png
  doc/user_guide/images/plot_images_eds_cmap_list.png
  doc/user_guide/images/plot_images_subplots.png
  doc/user_guide/visualisation.rst
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-False-False-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-False-False-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-False-True-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-False-True-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-True-False-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-True-False-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-True-True-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_False-True-True-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-False-False-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-False-False-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-False-True-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-False-True-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-True-False-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-True-False-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-True-True-False.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_True-True-True-True.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_list.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_list_w_diverging.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_make_cmap_bitfalse.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_make_cmap_bittrue.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_mpl_colors.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_multi_signal.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_multi_w_rgb.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_cmap_one_string.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_default.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_multiple_images_list_None-None.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_multiple_images_list_vmin0-vmax0.png
  hyperspy/tests/drawing/plot_signal2d/test_rgb_image_global.png
  hyperspy/tests/drawing/plot_signal2d/test_rgb_image_single.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next minor, status: waiting for author, type: New feature

#1685 Fix Line2DROI
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/widget.py
  hyperspy/roi.py
  hyperspy/tests/drawing/plot_widgets/test_plot_line2d.png
  hyperspy/tests/drawing/test_plot_widgets.py
Labels: release: next patch, status: WIP

#1821 Fix _linear_bin_loop numba issue.
  hyperspy/misc/array_tools.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1819 Add `doc` entry to extras_require to install doc dependencies
  doc/user_guide/install.rst
  setup.py
Labels: release: next patch, status: needs review, type: enhancement

#1737 NEW: hologram statistics
  doc/user_guide/electron_holography.rst
  hyperspy/_signals/hologram_image.py
  hyperspy/misc/holography/tools.py
  hyperspy/tests/signal/test_hologram_image.py
Labels: release: next minor, status: waiting for author, type: New feature
