Repository hyperspy/hyperspy, pull requests merged in 2018-05, with the labels that each got.

#1940 Fix typos in user guide: model.rst
  doc/user_guide/model.rst
Labels: affects: documentation, type: typo

#1936 Support for loading several root groups in EMD NCEM files
  hyperspy/io_plugins/emd.py
  hyperspy/tests/io/test_emd.py
Labels: release: next minor, status: needs review, type: enhancement

#1944 Fix compatibility with dask 0.17.4
  hyperspy/_components/gaussian.py
  hyperspy/_signals/complex_signal.py
Labels: affects: tests, release: next minor, status: needs review

#1949 Several docstring fixes in model.py
  hyperspy/model.py
Labels: affects: documentation, release: next patch, status: needs review, type: typo

#1951 Fix default formatting of `print_summary_statistics`
  hyperspy/signal.py
Labels: release: next patch, type: bug, type: bug-fix
