Repository hyperspy/hyperspy, pull requests merged in 2018-07, with the labels that each got.

#1953 Fix issue with applying function on masked data
  hyperspy/signal.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next patch, type: bug, type: bug-fix

#1960 Fix annular roi
  hyperspy/drawing/_widgets/circle.py
  hyperspy/tests/utils/test_roi.py
Labels: release: next patch, type: bug-fix

#1959 Enhancement: select and replot one axis in plot_images
  doc/user_guide/visualisation.rst
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next minor, type: enhancement

#1935 Fixes #1524: test time zone issue
  hyperspy/tests/misc/test_date_time_tools.py
Labels: affects: tests, release: next minor

#1939 Fix bug smooth savitzky golay
  hyperspy/drawing/mpl_he.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
Labels: affects: hyperspy_gui_ipywidgets, release: next minor, type: bug, type: bug-fix

#1870 Add support for hotkeys in higher navigation dimensions
  doc/conf.py
  doc/user_guide/visualisation.rst
  hyperspy/_components/volume_plasmon_drude.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/hologram_image.py
  hyperspy/_signals/signal1d.py
  hyperspy/axes.py
  hyperspy/defaults_parser.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/marker.py
  hyperspy/external/astroML/histtools.py
  hyperspy/io.py
  hyperspy/io_plugins/emd.py
  hyperspy/misc/eels/tools.py
  hyperspy/misc/holography/tools.py
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/tests/axes/test_axes_manager.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_io.py
  hyperspy/tests/io/test_mrcz.py
  hyperspy/tests/signal/test_hologram_image.py
  hyperspy/tests/signal/test_kramers_kronig_transform.py
  hyperspy/tests/signal/test_map_method.py
  hyperspy/tests/utils/test_roi.py
  hyperspy/ui_registry.py
Labels: release: next minor, type: bug-fix

#1994 Fix issue with figure rendering for signal1D.
  hyperspy/drawing/signal1d.py
Labels: release: next patch, type: bug-fix

#1986 Fix excess memory usage when performing reduce operations
  hyperspy/_signals/lazy.py
  hyperspy/tests/signal/test_tools.py
  setup.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#1999 Change logger level from "warning" to "info" when data are made contiguous
  hyperspy/_signals/lazy.py
  hyperspy/signal.py
Labels: release: next patch, type: enhancement

#2000 Fix plot_image for single nd image
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_single_image.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_images_single_image_stack.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: type: bug, type: bug-fix

#1934 Speed up reading chunked data from velox emd
  hyperspy/io_plugins/emd.py
Labels: release: next minor, status: needs review, type: bug-fix

#2008 Fix lazy FEI EMD SI
  hyperspy/misc/io/fei_stream_readers.py
Labels: status: needs review, type: bug-fix

#2010 Widget enhancement
  hyperspy/drawing/_widgets/circle.py
  hyperspy/drawing/_widgets/horizontal_line.py
  hyperspy/drawing/_widgets/label.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/_widgets/rectangles.py
  hyperspy/drawing/_widgets/vertical_line.py
  hyperspy/drawing/widget.py
  hyperspy/tests/drawing/plot_widgets/test_plot_ModifiableSpanSelector.png
  hyperspy/tests/drawing/plot_widgets/test_plot_range.png
  hyperspy/tests/drawing/plot_widgets/test_plot_range_Signal2D.png
  hyperspy/tests/drawing/test_plot_widgets.py
Labels: release: next minor, type: enhancement

#2009 Update warning for decomposition of non-float types
  hyperspy/learn/mva.py
  hyperspy/tests/mva/test_decomposition.py
Labels: release: next patch, type: bug, type: bug-fix

#2012 Fix lazy fei edx memory issue
  doc/user_guide/io.rst
  hyperspy/misc/io/fei_stream_readers.py
Labels: release: next minor, status: needs review

#2011 Fix roi widget direction
  hyperspy/roi.py
  hyperspy/tests/drawing/plot_roi/test_plot_circle_roi_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_circle_roi_signal.png
  hyperspy/tests/drawing/plot_roi/test_plot_line2d_roi_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_line2d_roi_signal.png
  hyperspy/tests/drawing/plot_roi/test_plot_point1D_axis_0.png
  hyperspy/tests/drawing/plot_roi/test_plot_point1D_axis_1.png
  hyperspy/tests/drawing/plot_roi/test_plot_point1D_axis_2.png
  hyperspy/tests/drawing/plot_roi/test_plot_point2D_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_point2D_signal.png
  hyperspy/tests/drawing/plot_roi/test_plot_rectangular_roi_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_rectangular_roi_signal.png
  hyperspy/tests/drawing/plot_roi/test_plot_spanroi_axis_0.png
  hyperspy/tests/drawing/plot_roi/test_plot_spanroi_axis_1.png
  hyperspy/tests/drawing/plot_roi/test_plot_spanroi_axis_2.png
  hyperspy/tests/drawing/test_plot_roi_widgets.py
  setup.py
Labels: release: next minor, status: needs review, type: bug, type: bug-fix, type: enhancement

#2004 Check microscope parameters only when necessary
  hyperspy/_signals/eels.py
  hyperspy/models/eelsmodel.py
Labels: release: next patch, type: bug-fix

#2015 Fix coveralls badge pointer to the wrong branch.
  README.rst
Labels: release: next minor, status: needs review

#2018 Update appveyor and coveralls badge to point to the correct branch.
  README.rst
Labels: release: next major, status: needs review

#2017 Update appveyor and coveralls badge to point to the correct branch.
  README.rst
Labels: release: next patch, status: needs review
