Repository hyperspy/hyperspy, pull requests merged in 2018-10, with the labels that each got.

#2063 Set hyperspy-*-gui requirement to last version
  setup.py
Labels: affects: hyperspy_gui_ipywidgets, affects: hyperspy_gui_traitsui, release: next patch, status: needs review, type: enhancement

#2065 Fix tests and tidy up CI
  .travis.yml
  appveyor.yml
  hyperspy/io_plugins/protochips.py
  hyperspy/misc/io/fei_stream_readers.py
  hyperspy/tests/io/protochips_data/invalid_protochips_file.csv
  hyperspy/tests/io/protochips_data/protochips_electrical.npy
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/misc/test_fei_stream_readers.py
  hyperspy/tests/signal/test_tools.py
  setup.py
Labels: affects: tests, release: next patch, status: needs review, type: bug-fix

#2076 Fix bug with missing metadata of EDS signal
  hyperspy/_signals/eds.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/signal/test_eds_tem.py
Labels: release: next patch, type: bug, type: bug-fix

#2064 bug-fix: Zeiss time, date, scale, new tifffile dep, tiff.py simplification
  hyperspy/external/tifffile.py
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
  hyperspy/tests/io/tiff_files/test_tiff_Zeiss_SEM_512pix.tif
Labels: release: next patch, status: waiting for author, type: bug-fix, type: enhancement

#2084 Fix typo and missing comma in signal2d.estimate_shift2D docstring
  hyperspy/_signals/signal2d.py
Labels: release: next patch, status: needs review, type: typo
