Repository hyperspy/hyperspy, pull requests merged in 2019-07, with the labels that each got.

#2219 Exclude dask 2.0 from install requirement since …
  setup.py
Labels: release: next minor

#2220 Drop python 3.5 support
  .travis.yml
  CHANGES.rst
  README.rst
  appveyor.yml
  setup.py
Labels: release: next minor, status: waiting for author

#2222 Explain possible warning when importing hyperspy in the user guide.
  doc/user_guide/getting_started.rst
  doc/user_guide/images/preferences.png
Labels: affects: documentation, release: next minor, status: needs review, type: enhancement

#2218 Fix docstrings in BaseSignal.
  doc/conf.py
  hyperspy/docstrings/plot.py
  hyperspy/docstrings/signal.py
  hyperspy/signal.py
Labels: affects: documentation, release: next minor, status: needs review

#2137 Rewritten Bleasdale componenet as Expression
  doc/user_guide/mva.rst
  hyperspy/_components/bleasdale.py
  hyperspy/tests/component/test_bleasdale.py
Labels: release: next minor, status: waiting for author, type: enhancement

#1778 Fix bug in bss component reversal
  hyperspy/learn/mva.py
  hyperspy/misc/utils.py
  hyperspy/tests/mva/test_bss.py
Labels: release: next minor, type: enhancement

#2215 Expression double power law
  hyperspy/_components/eels_double_power_law.py
  hyperspy/tests/component/test_double_power_law.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2216 Add gamma adjustment and fix contrast editor tool
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/complex_signal2d.py
  hyperspy/_signals/eds.py
  hyperspy/_signals/signal2d.py
  hyperspy/conftest.py
  hyperspy/defaults_parser.py
  hyperspy/docstrings/plot.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/image.py
  hyperspy/drawing/mpl_he.py
  hyperspy/drawing/mpl_hie.py
  hyperspy/drawing/utils.py
  hyperspy/misc/array_tools.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_log_negative_value_None.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_log_negative_value_gray.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_log_scale.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.3-0.7.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.3-1.2.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.5-0.7.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.5-1.2.png
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
Labels: release: next minor, status: needs review, type: bug, type: bug-fix, type: enhancement

#1989 Make Polynomial an Expression + bugfixes
  doc/user_guide/model.rst
  hyperspy/_components/expression.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/polynomial_deprecated.py
  hyperspy/_signals/signal1d.py
  hyperspy/component.py
  hyperspy/components1d.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/model.py
  hyperspy/models/edsmodel.py
  hyperspy/signal_tools.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/model/test_edsmodel.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signal/test_remove_background.py
Labels: release: next minor, status: needs review, type: bug-fix, type: enhancement

#2230 Fix rgb plotting
  hyperspy/drawing/image.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_rgb_image.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next patch, type: bug-fix

#2232 Catch deprecation warning for changes in the polynomial API.
  hyperspy/_signals/signal1d.py
  hyperspy/signal_tools.py
  hyperspy/tests/model/test_model.py
Labels: release: next patch, status: needs review

#2229 Fix changelog formatting.
  CHANGES.rst
Labels: affects: documentation, release: next patch, type: enhancement
