Repository hyperspy/hyperspy, pull requests merged in 2019-03, with the labels that each got.

#2128 Fix CI and deprecation warnings
  .travis.yml
  appveyor.yml
  hyperspy/io_plugins/emd.py
  hyperspy/tests/mva/test_decomposition.py
  hyperspy/tests/signal/test_fancy_indexing.py
  pytest.ini
Labels: affects: tests, release: next patch, status: needs review

#2143 Fix warning when plotting Signal1D with only zero values
  hyperspy/drawing/signal1d.py
Labels: release: next patch, status: needs review, type: bug-fix

#2144 Open plots will now be updated when using s.align_zero_loss_peak
  hyperspy/_signals/eels.py
Labels: release: next patch, status: needs review, type: bug-fix

#2147 Component logistic expression
  hyperspy/_components/logistic.py
Labels: release: next minor, type: enhancement

#2014 Friendler testing guide to new users
  doc/dev_guide.rst
Labels: affects: documentation, release: next minor, status: waiting for author, type: enhancement
