Repository hyperspy/hyperspy, pull requests merged in 2019-11, with the labels that each got.

#2281 Add option to skip SSL certificate verification to ``eelsdb``
  hyperspy/misc/eels/eelsdb.py
  hyperspy/tests/datasets/test_eelsdb.py
Labels: release: next minor, status: needs review, type: enhancement

#2258 Absorption correction for kfactors, z-factors and cross sections
  doc/user_guide/eds.rst
  hyperspy/_signals/eds.py
  hyperspy/_signals/eds_tem.py
  hyperspy/misc/eds/utils.py
  hyperspy/tests/signal/test_eds_tem.py
  hyperspy/tests/utils/test_eds.py
Labels: release: next minor, status: WIP, type: New feature

#2287 Remove vendored tifffile library
  .travis.yml
  appveyor.yml
  hyperspy/external/tifffile.py
  hyperspy/io_plugins/tiff.py
  setup.py
Labels: release: next patch, status: needs review

#2285 Fix dm4 test files
  hyperspy/tests/io/dm4_1D_data/test-1.dm4
  hyperspy/tests/io/dm4_1D_data/test-10.dm4
  hyperspy/tests/io/dm4_1D_data/test-11.dm4
  hyperspy/tests/io/dm4_1D_data/test-12.dm4
  hyperspy/tests/io/dm4_1D_data/test-13.dm4
  hyperspy/tests/io/dm4_1D_data/test-14.dm4
  hyperspy/tests/io/dm4_1D_data/test-2.dm4
  hyperspy/tests/io/dm4_1D_data/test-23.dm4
  hyperspy/tests/io/dm4_1D_data/test-27.dm4
  hyperspy/tests/io/dm4_1D_data/test-28.dm4
  hyperspy/tests/io/dm4_1D_data/test-3.dm4
  hyperspy/tests/io/dm4_1D_data/test-5.dm4
  hyperspy/tests/io/dm4_1D_data/test-6.dm4
  hyperspy/tests/io/dm4_1D_data/test-7.dm4
  hyperspy/tests/io/dm4_1D_data/test-8.dm4
  hyperspy/tests/io/dm4_1D_data/test-9.dm4
  hyperspy/tests/io/dm4_2D_data/test-1.dm4
  hyperspy/tests/io/dm4_2D_data/test-10.dm4
  hyperspy/tests/io/dm4_2D_data/test-11.dm4
  hyperspy/tests/io/dm4_2D_data/test-12.dm4
  hyperspy/tests/io/dm4_2D_data/test-13.dm4
  hyperspy/tests/io/dm4_2D_data/test-14.dm4
  hyperspy/tests/io/dm4_2D_data/test-2.dm4
  hyperspy/tests/io/dm4_2D_data/test-23.dm4
  hyperspy/tests/io/dm4_2D_data/test-27.dm4
  hyperspy/tests/io/dm4_2D_data/test-28.dm4
  hyperspy/tests/io/dm4_2D_data/test-3.dm4
  hyperspy/tests/io/dm4_2D_data/test-5.dm4
  hyperspy/tests/io/dm4_2D_data/test-6.dm4
  hyperspy/tests/io/dm4_2D_data/test-7.dm4
  hyperspy/tests/io/dm4_2D_data/test-8.dm4
  hyperspy/tests/io/dm4_2D_data/test-9.dm4
  hyperspy/tests/io/dm4_3D_data/test-1.dm4
  hyperspy/tests/io/dm4_3D_data/test-10.dm4
  hyperspy/tests/io/dm4_3D_data/test-11.dm4
  hyperspy/tests/io/dm4_3D_data/test-12.dm4
  hyperspy/tests/io/dm4_3D_data/test-13.dm4
  hyperspy/tests/io/dm4_3D_data/test-14.dm4
  hyperspy/tests/io/dm4_3D_data/test-2.dm4
  hyperspy/tests/io/dm4_3D_data/test-23.dm4
  hyperspy/tests/io/dm4_3D_data/test-27.dm4
  hyperspy/tests/io/dm4_3D_data/test-28.dm4
  hyperspy/tests/io/dm4_3D_data/test-3.dm4
  hyperspy/tests/io/dm4_3D_data/test-5.dm4
  hyperspy/tests/io/dm4_3D_data/test-6.dm4
  hyperspy/tests/io/dm4_3D_data/test-7.dm4
  hyperspy/tests/io/dm4_3D_data/test-8.dm4
  hyperspy/tests/io/dm4_3D_data/test-9.dm4
  hyperspy/tests/io/generate_dm_testing_files.py
Labels: release: next patch, status: needs review, type: bug-fix

#2283 Reduce memory usage of holography tests
  hyperspy/tests/signal/test_hologram_image.py
Labels: affects: tests, release: next patch

#2260 Fix coming tqdm api change
  hyperspy/external/progressbar.py
  setup.py
Labels: release: next patch, type: bug-fix

#1925 New Argand diagram for complex signals
  doc/user_guide/electron_holography.rst
  doc/user_guide/images/holography_argand_diagram.png
  doc/user_guide/tools.rst
  hyperspy/_signals/complex_signal.py
  hyperspy/misc/utils.py
  hyperspy/tests/misc/test_utils.py
  hyperspy/tests/signal/test_complex_signal.py
Labels: release: next minor, status: WIP, type: New feature
