Repository hyperspy/hyperspy, pull requests merged in 2019-09, with the labels that each got.

#2247 Fix issues with numpy 1.17 and dask 2.3.0
  .travis.yml
  ci/travis_install_with_conda.sh
  ci/travis_install_with_pip.sh
  ci/travis_setup_conda_linux.sh
  ci/travis_setup_conda_osx.sh
  hyperspy/_signals/eds.py
  hyperspy/component.py
  hyperspy/drawing/utils.py
  hyperspy/signal.py
  hyperspy/tests/misc/test_fei_stream_readers.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/ui_registry.py
Labels: affects: tests, release: next patch, type: bug, type: bug-fix

#2248 Fix typos
  hyperspy/roi.py
  hyperspy/ui_registry.py
Labels: release: next patch, type: typo

#2217 Fix #1712 and raise a warning when using map of ufuncs
  hyperspy/signal.py
  hyperspy/tests/signal/test_map_method.py
Labels: release: next minor, status: needs review, type: bug-fix

#2245 bug-fix_bcf_v2_1
  hyperspy/io_plugins/bruker.py
Labels: release: next patch, status: waiting for author, type: bug-fix

#2250 Fix real time bcf for large spectrum image on windows
  hyperspy/io_plugins/bruker.py
Labels: release: next patch, status: waiting for author, type: bug-fix

#2185 Estimate parameters for Lorentzian component
  hyperspy/_components/gaussian.py
  hyperspy/_components/lorentzian.py
  hyperspy/tests/component/test_gaussian.py
  hyperspy/tests/component/test_lorentzian.py
Labels: release: next minor, status: WIP, type: enhancement
