Repository hyperspy/hyperspy, pull requests merged in 2019-12, with the labels that each got.

#2261 Skew normal estimate parameters
  doc/user_guide/signal1d.rst
  hyperspy/_components/skew_normal.py
  hyperspy/_signals/signal1d.py
  hyperspy/signal_tools.py
  hyperspy/tests/component/test_skewnormal.py
  hyperspy/tests/signal/test_remove_background.py
Labels: release: next minor, status: needs review, type: enhancement

#2291 Remove erroneous line in docs
  doc/user_guide/visualisation.rst
Labels: release: next patch, type: bug-fix

#2288 Add ``__getitem__`` method to ROIs
  doc/user_guide/tools.rst
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/misc/utils.py
  hyperspy/models/model1d.py
  hyperspy/roi.py
  hyperspy/tests/misc/test_utils.py
  hyperspy/tests/utils/test_roi.py
Labels: release: next minor, status: needs review, type: enhancement

#2294 Fix issue with lambdify and FiniteSet
  hyperspy/component.py
  hyperspy/tests/model/test_model_as_dictionary.py
Labels: release: next patch, status: needs review, type: bug-fix
