Repository hyperspy/hyperspy, pull requests merged in 2019-06, with the labels that each got.

#2189 Fixes #2146: bcf file version reading
  hyperspy/io_plugins/bruker.py
Labels: release: next patch, type: bug-fix

#2193 Clarify and correct docstring plot of EDSSpectrum.
  hyperspy/_signals/eds.py
  hyperspy/docstrings/plot.py
Labels: affects: documentation, release: next patch

#2196 Fix saving ragged array in hspy format
  hyperspy/io_plugins/hspy.py
  hyperspy/tests/io/test_hdf5.py
  setup.py
Labels: release: next patch, type: bug-fix

#2197 Fix value error when plotting not finite value
  hyperspy/drawing/image.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next patch, type: bug, type: bug-fix

#2198 Fix race condition with channel switches in `as_signal`
  hyperspy/model.py
  hyperspy/tests/model/test_model.py
Labels: release: next patch, type: bug-fix

#2199 Fix installation link in dev guide.
  doc/dev_guide.rst
Labels: affects: documentation, release: next patch, status: needs review, type: bug-fix

#2200 Read date time DM SI
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/tests/io/dm4_3D_data/EELS_SI.dm4
  hyperspy/tests/io/test_dm3.py
Labels: release: next patch, type: enhancement

#2169 Fix get lines intensity model
  hyperspy/_signals/eds.py
  hyperspy/_signals/eds_tem.py
  hyperspy/model.py
  hyperspy/models/edsmodel.py
  hyperspy/tests/model/test_edsmodel.py
  hyperspy/tests/model/test_model.py
Labels: release: next patch, type: bug-fix, type: enhancement

#2160 Use ValidNumberElements instead of TotalNumberElements
  doc/user_guide/io.rst
  hyperspy/io.py
  hyperspy/io_plugins/fei.py
  hyperspy/tests/io/FEI_new/16x16-line_profile_horizontal_5x128x128_EDS_copy.emi
  hyperspy/tests/io/FEI_new/16x16-line_profile_horizontal_5x128x128_EDS_copy_1.ser
  hyperspy/tests/io/FEI_new/16x16-line_profile_horizontal_5x128x128_EDS_copy_2.ser
  hyperspy/tests/io/FEI_old/03_Scanning Preview.emi
  hyperspy/tests/io/FEI_old/03_Scanning Preview_1.ser
  hyperspy/tests/io/FEI_old/X - Au NP EELS_2.ser
  hyperspy/tests/io/test_fei.py
Labels: release: next minor, status: needs review, type: bug-fix

#2211 Fix heavised latex equation
  hyperspy/_components/heaviside.py
Labels: affects: documentation, release: next patch, status: needs review, type: bug-fix

#2202 Raise TypeError when plotting float16 image
  doc/user_guide/visualisation.rst
Labels: release: next patch, status: needs review

#2212 Clarify supported python version
  README.rst
  setup.py
Labels: release: next patch, status: needs review, type: bug-fix

#2186 Fix definition condition for expression component
  hyperspy/_components/expression.py
  hyperspy/_components/power_law.py
  hyperspy/tests/component/test_components.py
Labels: release: next patch, status: needs review, type: bug-fix, type: enhancement

#2214 Converted VolumePlasmonDrude to Expression using #2186
  hyperspy/_components/volume_plasmon_drude.py
  hyperspy/tests/component/test_volume_plasmon_drude.py
Labels: release: next minor, type: enhancement

#1933 New `BaseSignal.apodization()`
  doc/user_guide/images/hann_3d_order_ref_holo.png
  doc/user_guide/images/hann_window.png
  doc/user_guide/images/hologram_fft.png
  doc/user_guide/images/ref_hologram_fft.png
  doc/user_guide/tools.rst
  hyperspy/misc/math_tools.py
  hyperspy/signal.py
  hyperspy/tests/signal/test_apodization.py
  hyperspy/tests/signal/test_fourier_transform.py
Labels: release: next minor, status: waiting for author, type: New feature
