Repository hyperspy/hyperspy, pull requests merged in 2019-05, with the labels that each got.

#2158 Fix for last numpy release
  hyperspy/learn/mva.py
Labels: release: next patch, type: bug-fix

#2127 Fix dead mrc format specification link in docs
  doc/user_guide/io.rst
Labels: affects: documentation, release: next patch, type: bug-fix

#2159 Fix for mrcz 0.5.
  hyperspy/io_plugins/mrcz.py
Labels: release: next patch, type: bug-fix

#2155 Fix closing figure
  hyperspy/drawing/figure.py
  hyperspy/drawing/mpl_he.py
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/utils.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/drawing/test_figure_title.py
Labels: release: next patch, type: bug-fix

#2151 Improve error message when start and end value are equal in the crop method.
  hyperspy/signal.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next patch, type: enhancement

#2152 Fix docstring regarding loading Velox emd and tweak documentation.
  doc/user_guide/io.rst
  hyperspy/io.py
  hyperspy/io_plugins/emd.py
Labels: affects: documentation, release: next patch, type: bug-fix, type: enhancement

#2116 Fix docstring formatting
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/hologram_image.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/docstrings/signal.py
  hyperspy/drawing/_markers/horizontal_line.py
  hyperspy/drawing/_markers/horizontal_line_segment.py
  hyperspy/drawing/_markers/line_segment.py
  hyperspy/drawing/_markers/point.py
  hyperspy/drawing/_markers/rectangle.py
  hyperspy/drawing/_markers/text.py
  hyperspy/drawing/_markers/vertical_line.py
  hyperspy/drawing/_markers/vertical_line_segment.py
  hyperspy/model.py
  hyperspy/signal.py
  hyperspy/ui_registry.py
Labels: affects: documentation, release: next patch, type: bug, type: bug-fix

#2156 Bugfix remove background fast non interactive
  hyperspy/_components/eels_double_power_law.py
  hyperspy/_components/expression.py
  hyperspy/_components/offset.py
  hyperspy/_signals/signal1d.py
  hyperspy/component.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/signal/test_remove_background.py
Labels: release: next patch, status: needs review, type: bug-fix

#2150 Add tests to check creation of 1D components and fix a few bugs.
  hyperspy/_components/bleasdale.py
  hyperspy/_components/eels_vignetting.py
  hyperspy/_components/pes_see.py
  hyperspy/tests/component/test_components.py
Labels: release: next patch, status: needs review, type: bug-fix

#2166 Fix beam current zeiss
  doc/user_guide/metadata_structure.rst
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix, type: enhancement

#2149 Component Logistic documentation + test
  hyperspy/_components/logistic.py
  hyperspy/tests/component/test_logistic.py
Labels: release: next minor, type: enhancement

#2168 Improved documentation of Components.
  hyperspy/_components/arctan.py
  hyperspy/_components/error_function.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussian2d.py
  hyperspy/_components/heaviside.py
  hyperspy/_components/logistic.py
  hyperspy/_components/offset.py
  hyperspy/_components/rc.py
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/_components/skew_normal.py
  hyperspy/_components/volume_plasmon_drude.py
Labels: affects: documentation, type: enhancement

#2170 Remove pillow workaround in appveyor
  appveyor.yml
Labels: affects: tests, release: next patch

#2171 Don't change locale to read/write msa files
  hyperspy/io_plugins/msa.py
  hyperspy/tests/io/msa_files/example1_wrong_date.msa
  hyperspy/tests/io/test_msa.py
Labels: release: next patch, status: needs review, type: bug-fix

#2130 Make plot EDS maps easier
  doc/user_guide/eds.rst
  doc/user_guide/images/EDS_get_lines_intensity_all.png
  doc/user_guide/visualisation.rst
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next minor, type: enhancement

#2173 New `rename_pars` keyword argument for ``Expression`` component
  hyperspy/_components/expression.py
  hyperspy/tests/model/test_model_storing.py
Labels: release: next minor, status: needs review, type: enhancement

#1598 Model and component print_current_values() methods
  doc/user_guide/model.rst
  hyperspy/component.py
  hyperspy/misc/model_tools.py
  hyperspy/model.py
  hyperspy/tests/component/test_component_print_current.py
Labels: release: next minor, status: needs review, type: enhancement

#2090 Fix quant scaling error
  hyperspy/_signals/eds_tem.py
  hyperspy/tests/signal/test_eds_tem.py
Labels: release: next patch, status: needs review, type: bug-fix

#2175 Fix deprecation warning
  hyperspy/io_plugins/edax.py
  hyperspy/tests/io/test_protochips.py
Labels: release: next patch, type: bug-fix

#2019 Small documentation updates
  doc/README.txt
  doc/dev_guide.rst
  doc/user_guide/install.rst
  doc/user_guide/model.rst
  doc/user_guide/visualisation.rst
  setup.py
Labels: affects: documentation, release: next patch, type: bug, type: bug-fix

#2178 Remove "added in version X" from docs up to 1.1 + minor docs changes
  doc/user_guide/dielectric_function.rst
  doc/user_guide/eds.rst
  doc/user_guide/eels.rst
  doc/user_guide/events.rst
  doc/user_guide/getting_started.rst
  doc/user_guide/install.rst
  doc/user_guide/io.rst
  doc/user_guide/model.rst
  doc/user_guide/mva.rst
  doc/user_guide/signal1d.rst
  doc/user_guide/signal2d.rst
  doc/user_guide/tools.rst
  doc/user_guide/visualisation.rst
Labels: affects: documentation, release: next patch, type: enhancement

#2098 Fix bug when adding multidimensional marker to signal with more than 2 navigation dimensions with different size
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_markers.py
Labels: release: next patch, status: needs review, type: bug
