Repository hyperspy/hyperspy, pull requests merged in 2020-05, with the labels that each got.

#2387 Get EELS edges from a given energy window
  doc/user_guide/eels.rst
  hyperspy/_signals/eels.py
  hyperspy/tests/signal/test_eels.py
Labels: release: next minor, status: waiting for author, type: New feature

#2393 Fix import error with scikit-image 0.17.0
  hyperspy/_signals/signal2d.py
Labels: release: next patch, status: needs review

#2368 Absolute thickness estimation by EELS log-ratio method
  doc/user_guide/bibliography.rst
  doc/user_guide/eels.rst
  hyperspy/_signals/eels.py
  hyperspy/misc/eels/electron_inelastic_mean_free_path.py
  hyperspy/tests/signal/data/EELS_LL_linescan_simulated_thickness_variation.hspy
  hyperspy/tests/signal/data/EELS_ZLP_linescan_simulated_thickness_variation.hspy
  hyperspy/tests/signal/data/test_find_peaks1D_ohaver.hdf5
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/signal/test_find_peaks1D_ohaver.py
  setup.py
Labels: release: next minor, status: needs review, type: enhancement

#2391 Improve thread-based parallelism behaviour
  doc/user_guide/signal2d.rst
  doc/user_guide/tools.rst
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/hologram_image.py
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/docstrings/signal.py
  hyperspy/model.py
  hyperspy/signal.py
  hyperspy/tests/signal/test_2D_tools.py
Labels: release: next minor, status: needs review, type: enhancement

#2390 Relocate get_edges_near_energy()
  doc/user_guide/eels.rst
  hyperspy/_signals/eels.py
  hyperspy/misc/eels/tools.py
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/utils/test_eels.py
Labels: release: next minor, status: WIP, type: New feature

#2350 Clarify documentation load functions
  doc/user_guide/index.rst
  doc/user_guide/interactive_operations_ROIs.rst
  doc/user_guide/io.rst
  doc/user_guide/signal.rst
  hyperspy/_signals/signal1d.py
  hyperspy/io.py
Labels: affects: documentation, release: next minor, status: needs review, type: bug-fix, type: enhancement

#2400 updated FDA in user guide + add. corrections
  doc/user_guide/axes.rst
  hyperspy/axes.py
  hyperspy/signal.py
Labels: affects: documentation, type: New feature

#2403 Fix test broken with sympy >=1.6
  hyperspy/_components/expression.py
Labels: release: next patch, status: needs review

#2404 Add Gaussian2D properties
  hyperspy/_components/gaussian2d.py
  hyperspy/tests/component/test_gaussian2d.py
Labels: release: next minor, type: enhancement
