Repository hyperspy/hyperspy, pull requests merged in 2020-07, with the labels that each got.

#2432 Arctan expression
  doc/user_guide/model.rst
  hyperspy/_components/arctan.py
  hyperspy/_components/eels_arctan.py
  hyperspy/datasets/artificial_data.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/tests/component/test_EELSarctan.py
  hyperspy/tests/component/test_arctan.py
Labels: release: next minor, type: enhancement

#2410 .sur and .pro files support
  doc/user_guide/io.rst
  hyperspy/exceptions.py
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/io_plugins/sur.py
  hyperspy/tests/io/sur_data/test_RGB.sur
  hyperspy/tests/io/sur_data/test_profile.pro
  hyperspy/tests/io/sur_data/test_spectra.pro
  hyperspy/tests/io/sur_data/test_spectral_map.sur
  hyperspy/tests/io/sur_data/test_spectral_map_compressed.sur
  hyperspy/tests/io/sur_data/test_spectrum.pro
  hyperspy/tests/io/sur_data/test_spectrum_compressed.pro
  hyperspy/tests/io/sur_data/test_surface.sur
  hyperspy/tests/io/test_sur.py
Labels: release: next minor, status: WIP, type: New feature

#2328 Nexus io plugin
  doc/user_guide/io.rst
  hyperspy/io.py
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/nexus.py
  hyperspy/tests/io/nexus_files/nexus_dls_example.nxs
  hyperspy/tests/io/nexus_files/nexus_dls_example_no_axes.nxs
  hyperspy/tests/io/nexus_files/saved_multi_signal.nxs
  hyperspy/tests/io/nexus_files/simple_signal.nxs
  hyperspy/tests/io/test_nexus_hdf.py
Labels: release: next minor, status: WIP, type: New feature

#2289 Add support for reading EMPAD files.
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/empad.py
  hyperspy/io_plugins/fei.py
  hyperspy/misc/io/tools.py
  hyperspy/tests/io/empad_data/map4x4.xml
  hyperspy/tests/io/empad_data/stack_images.xml
  hyperspy/tests/io/test_empad.py
Labels: release: next minor, status: needs review, type: New feature

#2331 Fix "0" not being printed with print_current_values
  hyperspy/misc/model_tools.py
  hyperspy/tests/component/test_component_print_current.py
Labels: release: next patch, status: waiting for author, type: bug, type: bug-fix

#2416 Improve installation documentation
  doc/user_guide/install.rst
Labels: affects: documentation, release: next minor, status: needs review

#2439 IO user guide fixes
  doc/user_guide/io.rst
Labels: affects: documentation, release: next minor, status: needs review, type: bug-fix

#2446 Fix matplotlib 3.3.0
  hyperspy/drawing/_widgets/horizontal_line.py
  hyperspy/drawing/_widgets/label.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/_widgets/vertical_line.py
  hyperspy/drawing/image.py
  hyperspy/drawing/utils.py
Labels: affects: tests, release: next patch, status: waiting for author, type: bug-fix

#2434 Correct warning message for signal types
  hyperspy/io.py
  hyperspy/signal.py
  hyperspy/tests/signal/test_assign_subclass.py
Labels: release: next minor, type: bug-fix

#2447 Add project_urls metadata to setup.py and remove some obsolete info
  hyperspy/Release.py
  setup.py
Labels: release: next patch, status: needs review, type: enhancement

#2449 Rename hyperspy/tests/mva/ to hyperspy/tests/learn/
  hyperspy/tests/learn/__init__.py
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/learn/test_export.py
  hyperspy/tests/learn/test_lazy_decomposition.py
  hyperspy/tests/learn/test_learning_results.py
  hyperspy/tests/learn/test_mlpca.py
  hyperspy/tests/learn/test_ornmf.py
  hyperspy/tests/learn/test_rpca.py
  hyperspy/tests/learn/test_svd_pca.py
  hyperspy/tests/learn/test_whitening.py
  setup.py
Labels: release: next minor, status: needs review

#2396 Add prismatic reading support
  doc/user_guide/io.rst
  hyperspy/io.py
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/usid_hdf5.py
  hyperspy/tests/io/emd_files/Si100_1x1x3-zStart5.43.emd
  hyperspy/tests/io/emd_files/Si100_1x1x3-zStart6.7875.emd
  hyperspy/tests/io/emd_files/Si100_2D_3D_DPC_potential_2slices.emd
  hyperspy/tests/io/emd_files/Si100_2x1x1_3D.emd
  hyperspy/tests/io/emd_files/Si100_3D.emd
  hyperspy/tests/io/emd_files/Si100_4D.emd
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_emd_prismatic.py
  hyperspy/tests/io/test_usid.py
Labels: release: next minor, status: needs review, type: enhancement

#2453 Fix duplicate and unused imports
  hyperspy/drawing/_widgets/label.py
  hyperspy/drawing/image.py
  hyperspy/drawing/tiles.py
  hyperspy/io_plugins/msa.py
  hyperspy/io_plugins/sur.py
  hyperspy/misc/holography/tools.py
  hyperspy/tests/io/test_mrcz.py
  hyperspy/tests/io/test_phenom.py
  hyperspy/utils/__init__.py
  hyperspy/utils/eds.py
  hyperspy/utils/markers.py
  hyperspy/utils/material.py
  hyperspy/utils/model_selection.py
  hyperspy/utils/parallel_pool.py
  hyperspy/utils/plot.py
  hyperspy/utils/roi.py
  hyperspy/utils/samfire.py
  setup.cfg
Labels: release: next minor, type: enhancement

#2414 Update plot spectra
  doc/user_guide/images/interactive_profiles.gif
  doc/user_guide/visualisation.rst
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal1d/test_plot_spectra_auto_update.png
  hyperspy/tests/drawing/test_plot_signal1d.py
Labels: release: next minor, status: needs review, type: enhancement

#2444 Fix offset signal EMPAD.
  hyperspy/io_plugins/empad.py
  hyperspy/tests/io/test_empad.py
Labels: release: next minor, status: needs review, type: bug-fix

#2441 Improve m.fit() functionality
  doc/user_guide/eels.rst
  doc/user_guide/model.rst
  doc/user_guide/signal.rst
  hyperspy/docstrings/model.py
  hyperspy/model.py
  hyperspy/models/edsmodel.py
  hyperspy/models/eelsmodel.py
  hyperspy/models/model1d.py
  hyperspy/models/model2d.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_model.py
  hyperspy/tests/model/test_edsmodel.py
  hyperspy/tests/model/test_fitting.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/model/test_model2d.py
  hyperspy/tests/model/test_model_selection_criteria.py
  hyperspy/tests/signal/test_tools.py
  setup.py
Labels: release: next minor, status: needs review, type: enhancement

#2455 Partial improvement to the model fitting chapter
  doc/user_guide/model.rst
Labels: affects: documentation, release: next minor, status: needs review, type: enhancement

#2307 Remove background return model
  hyperspy/_components/doniach.py
  hyperspy/_components/eels_vignetting.py
  hyperspy/_components/pes_voigt.py
  hyperspy/_components/split_pvoigt.py
  hyperspy/_components/voigt.py
  hyperspy/_signals/signal1d.py
  hyperspy/datasets/artificial_data.py
  hyperspy/drawing/signal1d.py
  hyperspy/events.py
  hyperspy/misc/utils.py
  hyperspy/model.py
  hyperspy/signal_tools.py
  hyperspy/tests/component/test_doniach.py
  hyperspy/tests/component/test_splitvoigt.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/signal/test_remove_background.py
Labels: affects: hyperspy_gui_ipywidgets, affects: hyperspy_gui_traitsui, release: next minor, status: waiting for author, type: enhancement

#1497 NEW_find_peaks_2D
  doc/conf.py
  doc/user_guide/bibliography.rst
  doc/user_guide/images/find_peaks2D.png
  doc/user_guide/signal2d.rst
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal2d.py
  hyperspy/axes.py
  hyperspy/drawing/figure.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/tests/signal/test_find_peaks1D_ohaver.py
  hyperspy/tests/signal/test_find_peaks2D.py
  hyperspy/tests/signal/test_map_method.py
  hyperspy/utils/peakfinders2D.py
  setup.py
Labels: release: next minor, status: needs review, type: New feature

#2456 Better support for histogram bin estimation
  hyperspy/_signals/lazy.py
  hyperspy/docstrings/signal.py
  hyperspy/drawing/utils.py
  hyperspy/external/astroML/bayesian_blocks.py
  hyperspy/external/astroML/histtools.py
  hyperspy/external/astropy/LICENSE.RST
  hyperspy/external/astropy/__init__.py
  hyperspy/external/astropy/bayesian_blocks.py
  hyperspy/external/astropy/histogram.py
  hyperspy/misc/array_tools.py
  hyperspy/misc/hist_tools.py
  hyperspy/samfire_utils/global_strategies.py
  hyperspy/samfire_utils/segmenters/histogram.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.3-0.7.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.3-1.2.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.5-0.7.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_contrast_editor_0.5-1.2.png
  hyperspy/tests/misc/test_hist_tools.py
  hyperspy/tests/samfire/test_histogram_segmenter.py
  setup.py
Labels: release: next minor, status: needs review, type: bug-fix, type: enhancement
