Repository hyperspy/hyperspy, pull requests merged in 2020-08, with the labels that each got.

#2458 Change Numba optional dependency to required
  doc/dev_guide/speeding_up_code.rst
  doc/user_guide/io.rst
  doc/user_guide/signal.rst
  doc/user_guide/signal2d.rst
  hyperspy/decorators.py
  hyperspy/misc/array_tools.py
  hyperspy/misc/io/fei_stream_readers.py
  hyperspy/utils/peakfinders2D.py
  setup.py
Labels: release: next minor

#2461 Add random_state argument to functions that return stochastic output
  hyperspy/datasets/artificial_data.py
  hyperspy/learn/ornmf.py
  hyperspy/learn/rpca.py
  hyperspy/misc/math_tools.py
  hyperspy/samfire.py
  hyperspy/signal.py
  hyperspy/tests/misc/test_math_tools.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next minor, type: enhancement

#2203 Kmeans cluster analysis
  doc/user_guide/bibliography.rst
  doc/user_guide/cluster.rst
  doc/user_guide/images/clustering_Gap.png
  doc/user_guide/images/clustering_data.png
  doc/user_guide/images/clustering_decomposition_loadings.png
  doc/user_guide/images/clustering_gaussian_centres.png
  doc/user_guide/images/clustering_gaussian_centres_centroid.png
  doc/user_guide/images/clustering_gaussian_centres_labels.png
  doc/user_guide/images/clustering_gaussian_centres_mean.png
  doc/user_guide/images/clustering_labels.png
  doc/user_guide/images/clustering_scree_plot.png
  doc/user_guide/model.rst
  doc/user_guide/mva.rst
  hyperspy/docstrings/signal.py
  hyperspy/learn/mva.py
  hyperspy/misc/machine_learning/import_sklearn.py
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_distances_nav1_sig1.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_distances_nav2_sig2.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_labels_nav1_sig1.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_labels_nav2_sig1.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_labels_nav2_sig2.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_metric.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_signals_nav1_sig1.png
  hyperspy/tests/drawing/plot_mva/test_plot_cluster_signals_nav2_sig1.png
  hyperspy/tests/drawing/test_plot_mva.py
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/learn/test_cluster.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/misc/test_utils.py
Labels: release highlight, release: next minor, status: needs review, type: New feature

#2466 Add comp_label deprecation to cluster plotting methods
  hyperspy/signal.py
Labels: release: next minor, status: needs review

#2418 A method to print edge energy interactively
  doc/user_guide/eels.rst
  doc/user_guide/images/EELS_edges_at_energy.png
  hyperspy/_signals/eels.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/misc/eels/tools.py
  hyperspy/misc/label_position.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/plot_markers/test_plot_eels_labels.png
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/signal/test_tools.py
  hyperspy/tests/utils/test_eels.py
Labels: release highlight, release: next minor, status: needs review, type: New feature

#2468 Update docs to close #1624
  doc/user_guide/io.rst
  doc/user_guide/model.rst
Labels: affects: documentation, type: bug-fix

#2467 Uppercase acronyms
  doc/user_guide/big_data.rst
  doc/user_guide/model.rst
  doc/user_guide/mva.rst
  doc/user_guide/visualisation.rst
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/lazy.py
  hyperspy/docstrings/model.py
  hyperspy/learn/mva.py
  hyperspy/learn/whitening.py
  hyperspy/model.py
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/learn/test_lazy_decomposition.py
  hyperspy/tests/learn/test_learning_results.py
  hyperspy/tests/learn/test_mlpca.py
  hyperspy/tests/learn/test_ornmf.py
  hyperspy/tests/learn/test_rpca.py
  hyperspy/tests/learn/test_whitening.py
  hyperspy/tests/model/test_fitting.py
Labels: release: next minor, status: needs review, type: API change

#2356 Add autoscale to plot
  doc/user_guide/visualisation.rst
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/complex_signal2d.py
  hyperspy/_signals/eds.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/datasets/artificial_data.py
  hyperspy/defaults_parser.py
  hyperspy/docstrings/plot.py
  hyperspy/drawing/image.py
  hyperspy/drawing/mpl_he.py
  hyperspy/drawing/mpl_hie.py
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/utils.py
  hyperspy/misc/test_utils.py
  hyperspy/roi.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/datasets/test_artificial_data.py
  hyperspy/tests/drawing/plot_markers/test_plot_eels_labels.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_autoscale_.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_autoscale_v.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_autoscale_x.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_autoscale_xv.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_autoscale_.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_autoscale_v.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_autoscale_xv.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_autoscale_xy.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_autoscale_xyv.png
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
  hyperspy/tests/drawing/test_plot_signal.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release highlight, release: next minor, status: needs review, type: enhancement

#2472 Tidy up long-running and duplicated tests
  hyperspy/tests/learn/test_cluster.py
  hyperspy/tests/signal/test_1D.py
  hyperspy/tests/signal/test_2D.py
  hyperspy/tests/signal/test_3D.py
  hyperspy/tests/signal/test_4D.py
  hyperspy/tests/signal/test_edges_range.py
  hyperspy/tests/signal/test_fourier_transform.py
  hyperspy/tests/signal/test_hologram_image.py
  hyperspy/tests/signal/test_lazy_tools.py
  hyperspy/tests/signal/test_linear_rebin.py
  hyperspy/tests/signal/test_spike_removal_tool.py
  hyperspy/tests/signal/test_tools.py
  hyperspy/tests/signal/test_transpose.py
Labels: affects: tests, release: next patch, status: needs review

#2479 Change rng.random to rng.random_sample
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/learn/test_cluster.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/learn/test_lazy_decomposition.py
  hyperspy/tests/learn/test_learning_results.py
  hyperspy/tests/signal/test_fourier_transform.py
Labels: affects: tests, release: next patch, status: needs review, type: bug-fix

#2482 Patch for .histogram method, repull of #2477
  hyperspy/misc/hist_tools.py
  hyperspy/tests/misc/test_hist_tools.py
Labels: release: next patch, status: needs review, type: bug-fix

#2484 Fix axes tifffile
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
  hyperspy/tests/signal/test_1D_tools.py
Labels: affects: tests, release: next patch, status: needs review, type: bug-fix

#2473 Build wheels
  .github/workflows/release.yml
  hyperspy/Release.py
  pyproject.toml
  setup.py
Labels: release: next patch, status: needs review, type: enhancement

#2494 mpfit clean-up
  hyperspy/external/mpfit/mpfit.py
  hyperspy/external/mpfit/mpfitexpr.py
  hyperspy/model.py
  hyperspy/tests/external/test_mpfit.py
Labels: release: next minor, status: needs review, type: enhancement

#2497 Remove physical_constants.py and use scipy.constants instead
  hyperspy/misc/eels/hartree_slater_gos.py
  hyperspy/misc/eels/hydrogenic_gos.py
  hyperspy/misc/math_tools.py
  hyperspy/misc/physical_constants.py
  hyperspy/misc/physics_tools.py
  hyperspy/tests/misc/test_physics_tools.py
Labels: affects: tests, release: next patch, type: enhancement

#2496 Histogram warning fix
  hyperspy/misc/hist_tools.py
  hyperspy/signal.py
Labels: release: next patch, status: needs review, type: bug-fix

#2486 Remove signal_type='image' for velox emd and phenom
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/phenom.py
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_phenom.py
Labels: release: next patch, status: needs review, type: bug-fix

#2498 Update dev-guide following #2485
  doc/dev_guide/speeding_up_code.rst
  doc/dev_guide/testing.rst
  doc/dev_guide/writing_docs.rst
Labels: affects: documentation, release: next patch, status: needs review

#2499 Add nightly merge RnM into non_uniform_axes
  .github/workflows/nightly-merge_non_uniform.yml
Labels: status: needs review, type: enhancement

#2500 Use latest and concept DOI in docs instead of the specific one
  README.rst
  doc/citing.rst
Labels: affects: documentation, status: needs review, type: enhancement

#2501 Fix y-limits when plotting several lines
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/signal1d.py
  hyperspy/model.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/plot_signal_tools/test_plot_BackgroundRemoval.png
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
Labels: release: next patch, status: needs review, type: bug-fix, type: enhancement

#2502 Warn on mismatched axis calibrations when stacking
  hyperspy/axes.py
  hyperspy/misc/axis_tools.py
  hyperspy/misc/signal_tools.py
  hyperspy/misc/utils.py
  hyperspy/tests/utils/test_stack.py
  hyperspy/tests/utils/test_stack_calibration.py
Labels: release: next patch, status: needs review, type: enhancement

#2508 Remove leftover debugging print
  hyperspy/roi.py
Labels: release: next patch, status: needs review, type: bug-fix

#2509 Fix set signal range
  hyperspy/models/model1d.py
  hyperspy/tests/drawing/plot_model/test_fit_EELS_convolved_False.png
  hyperspy/tests/drawing/plot_model/test_fit_EELS_convolved_True.png
  hyperspy/tests/drawing/plot_signal_tools/test_plot_BackgroundRemoval.png
  hyperspy/tests/model/test_chi_squared.py
  hyperspy/tests/model/test_eelsmodel.py
  hyperspy/tests/model/test_fitting.py
Labels: release: next patch, status: needs review, type: bug-fix

#2514 fix gradients and use numpy function for heaviside expression (patch)
  hyperspy/_components/heaviside.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_heaviside.py
Labels: release: next patch, status: needs review, type: bug-fix

#2510 Fix oldest versions build
  .travis.yml
  doc/dev_guide/testing.rst
  doc/user_guide/install.rst
  hyperspy/_signals/signal1d.py
  hyperspy/misc/lowess_smooth.py
  hyperspy/signal_tools.py
  hyperspy/tests/signal/test_1D_tools.py
  setup.py
Labels: affects: tests, release: next patch, status: needs review, type: bug-fix

#2515 Remove reference to googlegroup
  .github/CONTRIBUTING.md
  doc/user_guide/install.rst
Labels: affects: documentation, release: next patch, status: waiting for author

#2517 Add link to rolling release linux dists
  doc/user_guide/install.rst
Labels: affects: documentation, release: next patch, status: needs review

#2503 Remove parallel argument from .as_signal
  hyperspy/model.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/samfire/test_samfire.py
Labels: release: next patch, status: needs review, type: bug-fix
