Repository hyperspy/hyperspy, pull requests merged in 2020-11, with the labels that each got.

#2304 hspy read support for non linear axis and more error catches
  doc/user_guide/axes.rst
  doc/user_guide/signal.rst
  hyperspy/axes.py
  hyperspy/io.py
  hyperspy/io_plugins/README
  hyperspy/io_plugins/blockfile.py
  hyperspy/io_plugins/bruker.py
  hyperspy/io_plugins/dens.py
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/io_plugins/edax.py
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/empad.py
  hyperspy/io_plugins/fei.py
  hyperspy/io_plugins/hspy.py
  hyperspy/io_plugins/image.py
  hyperspy/io_plugins/mrc.py
  hyperspy/io_plugins/mrcz.py
  hyperspy/io_plugins/msa.py
  hyperspy/io_plugins/netcdf.py
  hyperspy/io_plugins/nexus.py
  hyperspy/io_plugins/phenom.py
  hyperspy/io_plugins/protochips.py
  hyperspy/io_plugins/ripple.py
  hyperspy/io_plugins/semper_unf.py
  hyperspy/io_plugins/sur.py
  hyperspy/io_plugins/tiff.py
  hyperspy/io_plugins/usid_hdf5.py
  hyperspy/signal.py
  hyperspy/tests/axes/test_conversion_units.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/io/test_blockfile.py
  hyperspy/tests/io/test_edax.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/io/test_io.py
  hyperspy/tests/io/test_phenom.py
  hyperspy/tests/test_dictionary_tree_browser.py
Labels: non-linear axis, release: next minor, status: WIP

#2567 added support for DPC
  doc/user_guide/io.rst
  hyperspy/io_plugins/emd.py
  hyperspy/tests/io/emd_files/fei_example_dpc_titles.emd
  hyperspy/tests/io/test_emd.py
Labels: release: next patch, type: bug-fix

#2574 small fix to USID writer
  hyperspy/io_plugins/usid_hdf5.py
Labels: release: next patch, status: WIP, type: bug-fix

#2578 Propagate the lazy argument when loading metadata
  hyperspy/io_plugins/nexus.py
  hyperspy/tests/io/test_nexus_hdf.py
Labels: release: next patch, status: waiting for author, type: bug-fix

#2563 Fix default value autoscale
  hyperspy/drawing/image.py
  hyperspy/drawing/mpl_he.py
Labels: release: next patch, status: needs review, type: bug-fix

#2560 Model plotting improvement and fixes
  hyperspy/_components/expression.py
  hyperspy/drawing/signal1d.py
  hyperspy/events.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/models/model2d.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/drawing/test_plot_model.py
  hyperspy/tests/model/test_fit_component.py
  hyperspy/tests/model/test_model2d.py
  hyperspy/tests/test_events.py
Labels: release: next patch, status: needs review, type: bug-fix, type: enhancement

#2583 Use prettytable dependencies instead of ptable
  conda_environment.yml
  setup.py
Labels: release: next patch, status: needs review

#2576 Plotting fixes
  hyperspy/drawing/image.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
Labels: release: next patch, status: needs review, type: bug-fix

#2579 Fix saving tiff file for signal with Å units
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
Labels: release: next patch, status: needs review, type: bug-fix

#2585 Fix saving tiff file with angstrom units (workaround encoding issue).
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
Labels: type: bug-fix

#2437 Docs: hspy compression saving times and chunking order
  doc/user_guide/big_data.rst
  doc/user_guide/io.rst
  hyperspy/io_plugins/hspy.py
  hyperspy/tests/io/test_hdf5.py
  setup.py
Labels: affects: documentation, release: next patch, status: waiting for author

#2569 Support h5py 3.0
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/hspy.py
  hyperspy/io_plugins/nexus.py
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/io/test_io.py
  hyperspy/tests/io/test_nexus_hdf.py
Labels: release: next patch, status: needs review, type: bug-fix

#2587 Skip test with old tifffile
  hyperspy/tests/io/test_tiff.py
Labels: release: next patch

#2577 Package missing test file
  setup.py
Labels: affects: tests, release: next patch, type: bug-fix

#2592 Move test suite to GitHub actions
  .github/workflows/tests.yml
  .travis.yml
  doc/dev_guide/testing.rst
  doc/user_guide/io.rst
  hyperspy/io_plugins/hspy.py
  hyperspy/tests/io/test_hdf5.py
  setup.py
Labels: affects: tests, status: needs review

#2589 Update installation instructions
  doc/user_guide/install.rst
Labels: affects: documentation, status: needs review
