Repository hyperspy/hyperspy, pull requests merged in 2020-06, with the labels that each got.

#2408 Document ScaleableFixedPattern
  doc/user_guide/model.rst
Labels: affects: documentation, release: next patch, type: enhancement

#2407 Print a table about identified EELS edges
  doc/user_guide/eels.rst
  hyperspy/_signals/eels.py
  hyperspy/misc/elements.py
  hyperspy/tests/signal/test_eels.py
Labels: release: next minor, status: waiting for author, type: New feature

#2411 Tidy up test suite and fix dependencies
  azure-pipelines.yml
  conda_environment.yml
  conda_environment_dev.yml
  hyperspy/axes.py
  hyperspy/drawing/image.py
  hyperspy/tests/__init__.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/datasets/test_eelsdb.py
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/io/test_usid.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/samfire/test_goodness_of_fit_tests.py
  hyperspy/tests/samfire/test_samfire.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/tests/signal/test_complex_signal.py
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/signal/test_kramers_kronig_transform.py
  hyperspy/tests/signal/test_map_method.py
  hyperspy/tests/signal/test_remove_background.py
  setup.py
Labels: release: next minor, status: needs review, type: bug-fix, type: enhancement

#2423 Update pytest manually.
  .travis.yml
Labels: affects: tests, release: next patch, status: needs review

#2430 Use a simpler dataset for BSS testing
  hyperspy/misc/machine_learning/tools.py
  hyperspy/tests/mva/test_bss.py
Labels: release: next minor, type: enhancement

#2431 Fix numpy1.19
  hyperspy/_signals/complex_signal.py
  hyperspy/axes.py
  hyperspy/io_plugins/bruker.py
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/hspy.py
  hyperspy/tests/io/test_hdf5.py
Labels: release: next patch, status: waiting for author, type: bug-fix

#2435 Fix bug in `signal.split`
  hyperspy/signal.py
  hyperspy/tests/signal/test_tools.py
  hyperspy/tests/utils/test_stack.py
Labels: release: next patch, type: bug-fix

#2262 Convert heaviside step function component to expression
  hyperspy/_components/heaviside.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_heaviside.py
  hyperspy/tests/mva/test_bss.py
Labels: release: next minor, status: needs review, type: enhancement
