Repository hyperspy/hyperspy, pull requests merged in 2020-03, with the labels that each got.

#1807 Fancy metadata
  hyperspy/misc/utils.py
  hyperspy/tests/test_dictionary_tree_browser.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2323 Fix tiff io plugin
  hyperspy/io_plugins/tiff.py
Labels: release: next patch, status: needs review

#1585 Fix #1575, test_compilers.c location
  setup.py
Labels: release: next patch, status: waiting for author, type: bug, type: bug-fix

#2322 Fix import io plugins
  hyperspy/io_plugins/__init__.py
Labels: release: next patch, type: bug, type: bug-fix

#2324 Update installation instructions
  doc/user_guide/install.rst
  hyperspy/_signals/common_signal1d.py
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/eels.py
  hyperspy/axes.py
  hyperspy/component.py
  hyperspy/components1d.py
  hyperspy/components2d.py
  hyperspy/drawing/utils.py
  hyperspy/io_plugins/usid_hdf5.py
  hyperspy/misc/tv_denoise.py
  hyperspy/model.py
  hyperspy/roi.py
  hyperspy/signal.py
Labels: affects: documentation, release: next minor, type: enhancement
