Repository hyperspy/hyperspy, pull requests merged in 2020-04, with the labels that each got.

#2334 Add python38 to CI matrix.
  .travis.yml
  appveyor.yml
  setup.py
Labels: affects: tests

#1274 Enhancement: PCA on complex numbers
  hyperspy/learn/mva.py
  hyperspy/tests/mva/test_decomposition.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2336 Printing important decomposition information
  hyperspy/learn/mva.py
  hyperspy/tests/mva/test_decomposition.py
Labels: release: next minor, status: WIP, type: enhancement

#2348 Fix CI
  .travis.yml
Labels: affects: tests, release: next patch, status: needs review

#2035 ENH: Add subspace tracking to ORNMF (consistent with ORPCA)
  doc/user_guide/big_data.rst
  doc/user_guide/mva.rst
  hyperspy/_signals/lazy.py
  hyperspy/learn/mva.py
  hyperspy/learn/ornmf.py
  hyperspy/learn/rpca.py
  hyperspy/tests/mva/test_decomposition.py
  hyperspy/tests/mva/test_onmf.py
  hyperspy/tests/mva/test_ornmf.py
  hyperspy/tests/mva/test_rpca.py
Labels: release: next minor, status: waiting for author, type: New feature

#2254 Add colormap setting to preferences
  hyperspy/conftest.py
  hyperspy/defaults_parser.py
  hyperspy/docstrings/plot.py
  hyperspy/drawing/__init__.py
  hyperspy/drawing/mpl_he.py
  hyperspy/drawing/mpl_hie.py
  hyperspy/drawing/utils.py
  hyperspy/signal.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_navigator_colormap_None.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_navigator_colormap_gray.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_navigator_colormap_preference.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next minor, type: bug-fix, type: enhancement

#2327 Fix deprecation warning
  hyperspy/_components/voigt.py
  hyperspy/_signals/signal1d.py
  hyperspy/misc/eds/utils.py
  hyperspy/misc/material.py
  hyperspy/models/model1d.py
  hyperspy/tests/component/test_components2D.py
  hyperspy/tests/component/test_gaussianhf.py
  hyperspy/tests/model/test_edsmodel.py
  hyperspy/tests/model/test_fit_component.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/samfire/test_goodness_of_fit_tests.py
Labels: affects: tests, release: next minor, status: needs review, type: bug-fix

#2329 Improve error message roi interactive
  hyperspy/events.py
  hyperspy/misc/utils.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
Labels: release: next patch

#2326 asymmetric lineshapes for eds and xrf fitting
  doc/user_guide/model.rst
  hyperspy/_components/doniach.py
  hyperspy/_components/split_pvoigt.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/tests/component/test_doniach.py
  hyperspy/tests/component/test_splitvoigt.py
Labels: release: next minor, type: New feature

#2354 Fix typo docstring.
  hyperspy/signal.py
Labels: affects: documentation, release: next patch, type: bug, type: bug-fix

#2358 Performance improvements for estimate_shift_2D() and other FFTs
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal2d.py
  hyperspy/misc/math_tools.py
  hyperspy/samfire.py
  hyperspy/samfire_utils/samfire_pool.py
  hyperspy/signal.py
  hyperspy/tests/samfire/test_samfire.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2363 Add azure pipelines and remove appveyor
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  ci/travis_install_with_conda.sh
  ci/travis_install_with_pip.sh
  ci/travis_setup_conda_linux.sh
  ci/travis_setup_conda_osx.sh
  conda_environment.yml
  conda_environment_dev.yml
  setup.py
Labels: affects: tests, release: next patch

#2376 Renamed EELSCLEdge private attributes
  hyperspy/_components/eels_cl_edge.py
Labels: release: next patch, type: bug-fix

#2370 Updated docs on smart_fit
  doc/user_guide/eels.rst
  hyperspy/models/eelsmodel.py
Labels: affects: documentation, type: enhancement

#2352 Fix maximum-likelihood PCA method
  hyperspy/learn/mlpca.py
  hyperspy/learn/mva.py
  hyperspy/tests/mva/test_decomposition.py
  hyperspy/tests/mva/test_mlpca.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2369 Doc test suite
  .travis.yml
  doc/dev_guide/testing.rst
  doc/user_guide/images/azure_pipeline_artifacts.png
  hyperspy/samfire.py
  hyperspy/samfire_utils/samfire_pool.py
  hyperspy/tests/io/test_mrcz.py
  hyperspy/tests/samfire/test_samfire.py
Labels: affects: documentation, affects: tests, release: next patch, status: waiting for author, type: bug-fix

#2351 Phenom elid reader
  doc/user_guide/io.rst
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/phenom.py
  hyperspy/tests/io/phenom_data/Elid2Version0.elid
  hyperspy/tests/io/phenom_data/Elid2Version1.elid
  hyperspy/tests/io/test_phenom.py
Labels: release: next minor, status: waiting for author, type: New feature

#2378 (Re)enable code coverage and fail on sphinx warnings
  .travis.yml
Labels: release: next patch, status: needs review

#2379 Fix error message toolkit
  hyperspy/ui_registry.py
Labels: release: next patch, status: needs review, type: bug-fix

#2381 Combine pytest.ini and .coveragerc into setup.cfg
  .coveragerc
  doc/dev_guide/coding_style.rst
  doc/dev_guide/testing.rst
  doc/dev_guide/writing_docs.rst
  hyperspy/conftest.py
  pytest.ini
  setup.cfg
Labels: affects: documentation, affects: tests, release: next patch, status: needs review, type: enhancement
