Repository hyperspy/hyperspy, pull requests merged in 2020-12, with the labels that each got.

#2590 Add handling for CL metadata in DM reader
  doc/user_guide/io.rst
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/tests/io/dm4_1D_data/test-CL_spectrum-ccd.dm4
  hyperspy/tests/io/dm4_1D_data/test-CL_spectrum-pmt.dm4
  hyperspy/tests/io/dm4_2D_data/test-CL_spectrum-SI.dm4
  hyperspy/tests/io/test_dm3.py
Labels: release: next minor, status: WIP, type: enhancement

#2595 Add releasing guide
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGES.rst
  releasing_guide.md
Labels: affects: documentation, release: next patch, status: needs review, type: enhancement

#2570 Document setting signal range of Model2D using channel_switches
  doc/user_guide/model.rst
  hyperspy/tests/model/test_model2d.py
Labels: affects: documentation, release: next patch, status: needs review, type: bug-fix

#2603 Fix navigation mask issue with quantification of single spectrum
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/eels.py
  hyperspy/tests/signal/test_eds_tem.py
  hyperspy/tests/signal/test_eels.py
Labels: release: next minor, status: needs review, type: bug, type: bug-fix

#2599 Plot overlay images
  doc/user_guide/images/plot_images_overlay.png
  doc/user_guide/visualisation.rst
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-auto-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-auto-auto-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-auto-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-auto-label1-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-colors1-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-colors1-auto-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-colors1-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-colors1-label1-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-auto-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-auto-auto-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-auto-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-auto-label1-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-colors1-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-colors1-auto-off.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-colors1-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-colors1-label1-off.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next minor, status: WIP, type: New feature

#2386 Support for relative slicing
  doc/user_guide/signal.rst
  hyperspy/axes.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/signal/test_fancy_indexing.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2488 JEOL eds data plugins
  .github/workflows/tests.yml
  doc/user_guide/io.rst
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/jeol.py
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000000.img
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000001.map
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000002.map
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000003.map
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000004.map
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000005.map
  hyperspy/tests/io/JEOL_files/Sample/00_View000/View000_0000006.pts
  hyperspy/tests/io/JEOL_files/met03.EDS
  hyperspy/tests/io/JEOL_files/rawdata.ASW
  hyperspy/tests/io/test_jeol.py
Labels: release: next minor, status: waiting for author, type: New feature
