Repository hyperspy/hyperspy, pull requests merged in 2020-09, with the labels that each got.

#2519 setup.py package_data fixes
  setup.py
Labels: release: next patch, status: fix-submitted, status: needs review

#2523 Fix to make sure example signals are loaded read-only
  hyperspy/misc/example_signals_loading.py
Labels: release: next patch, status: fix-submitted, status: needs review

#2524 Keep edax zip test file
  .gitignore
  hyperspy/tests/io/test_edax.py
Labels: affects: tests, release: next patch, status: needs review, type: bug-fix

#2527 Update AUR information in install instructions
  doc/user_guide/install.rst
Labels: affects: documentation, release: next patch, status: needs review

#2528 Replace adhoc code with sphinx-toggleprompt
  doc/_static/copybutton.js
  doc/_static/jquery.js
  doc/conf.py
  setup.py
Labels: affects: documentation, release: next patch, status: needs review, type: bug, type: bug-fix

#2520 Support parallel test execution on CI
  .travis.yml
  azure-pipelines.yml
  conda_environment_dev.yml
  doc/dev_guide/testing.rst
  hyperspy/api.py
  hyperspy/conftest.py
  hyperspy/misc/array_tools.py
  hyperspy/misc/io/fei_stream_readers.py
  hyperspy/misc/lowess_smooth.py
  hyperspy/misc/machine_learning/import_sklearn.py
  hyperspy/tests/datasets/test_eelsdb.py
  hyperspy/tests/io/test_empad.py
  hyperspy/tests/misc/test_arraytools.py
  hyperspy/tests/misc/test_tv_denoise.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/tests/signal/test_hologram_image.py
  hyperspy/tests/signal/test_hologram_image_statistics.py
  hyperspy/tests/signal/test_image_contrast_editor_tool.py
  hyperspy/tests/signal/test_map_method.py
  hyperspy/utils/peakfinders2D.py
  setup.cfg
  setup.py
Labels: affects: tests, release: next patch, status: needs review

#2529 Fix for when .emi file has no AcquireDate
  hyperspy/io_plugins/fei.py
  hyperspy/tests/io/FEI_old/no_AcquireDate.emi
  hyperspy/tests/io/FEI_old/no_AcquireDate_1.ser
  hyperspy/tests/io/test_fei.py
Labels: release: next patch, status: fix-submitted, status: needs review, type: bug-fix

#2364 Fix live time change for EDS signals when summing along signal dimension
  hyperspy/_signals/eds.py
  hyperspy/tests/signal/test_eds_sem.py
  hyperspy/tests/signal/test_eds_tem.py
Labels: release: next patch, status: needs review, type: bug-fix

#2531 Defend against more .ser files than number of metadata elements present
  hyperspy/io_plugins/fei.py
  hyperspy/tests/io/FEI_old/more_ser_then_emi_metadata.emi
  hyperspy/tests/io/FEI_old/more_ser_then_emi_metadata_1.ser
  hyperspy/tests/io/FEI_old/more_ser_then_emi_metadata_2.ser
  hyperspy/tests/io/test_fei.py
Labels: release: next patch, status: fix-submitted, type: bug-fix

#2538 Update documentation on TIFF dtype
  doc/user_guide/io.rst
Labels: affects: documentation, release: next patch, status: needs review

#2539 Add warning on Windows and test to guard against #2320
  hyperspy/_signals/signal1d.py
  hyperspy/tests/signal/test_1D_tools.py
Labels: release: next patch, status: needs review, type: bug-fix

#2537 Initial support for pathlib
  doc/user_guide/io.rst
  hyperspy/_signals/signal1d.py
  hyperspy/component.py
  hyperspy/defaults_parser.py
  hyperspy/extensions.py
  hyperspy/io.py
  hyperspy/misc/config_dir.py
  hyperspy/misc/eels/hartree_slater_gos.py
  hyperspy/misc/example_signals_loading.py
  hyperspy/misc/io/tools.py
  hyperspy/misc/ipython_tools.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_model.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/io/test_io.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/misc/test_utils.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/signal/test_find_peaks1D_ohaver.py
  setup.cfg
Labels: release: next patch, status: needs review, type: enhancement

#2540 Add more function_nd methods
  hyperspy/_components/eels_arctan.py
  hyperspy/_components/heaviside.py
  hyperspy/_components/pes_core_line_shape.py
  hyperspy/_components/pes_see.py
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_pes_core_line_shape.py
  hyperspy/tests/component/test_pes_see.py
  hyperspy/tests/component/test_pes_voigt.py
  hyperspy/tests/model/test_model_as_dictionary.py
Labels: release: next patch, status: needs review, type: bug-fix, type: enhancement

#1412 Add filter_zero_loss_peak argument to spikes_removal_tool and fix one bug.
  doc/dev_guide/lazy_computations.rst
  doc/user_guide/signal1d.rst
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/docstrings/signal.py
  hyperspy/docstrings/signal1d.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/signal/test_spike_removal_tool.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next minor, status: waiting for author, type: bug-fix, type: enhancement

#2542 Mention HDF5 gms plugin to user guide
  doc/user_guide/io.rst
Labels: affects: documentation, release: next patch, status: needs review

#2543 Fix future and deprecation warning pyusid.
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/usid_hdf5.py
  hyperspy/tests/io/test_usid.py
  setup.py
Labels: release: next patch, status: needs review, type: bug-fix

#2544 Add download badges and fix azure pipeline badge
  README.rst
Labels: release: next patch, status: needs review, type: enhancement

#2546 Add monitor distribution section to dev guide.
  README.rst
  doc/dev_guide/useful_information.rst
Labels: affects: documentation, release: next patch, status: needs review

#2183 Vacuum mask eels
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/learn/mva.py
  hyperspy/misc/eds/utils.py
  hyperspy/signal.py
  hyperspy/tests/model/test_edsmodel.py
  hyperspy/tests/signal/test_eds_tem.py
  hyperspy/tests/signal/test_eels.py
  hyperspy/tests/signal/test_mask.py
Labels: release: next minor, status: needs review, type: New feature, type: bug-fix

#2548 Use hs.preferences for progress bar in LazySignal.compute()
  hyperspy/_signals/lazy.py
  hyperspy/tests/signal/test_lazy.py
Labels: release: next patch, status: needs review, type: bug-fix

#2512 Fix for #2452 - index-dependent plot error in non-uniform-axis branch
  hyperspy/drawing/widget.py
  hyperspy/tests/drawing/test_widget.py
Labels: non-linear axis, status: waiting for author, type: bug-fix

#2553 Fix mask decomposition eds
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/signal1d.py
  hyperspy/learn/mva.py
  hyperspy/misc/eds/utils.py
  hyperspy/signal.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/misc/test_eds_utils.py
  hyperspy/tests/signal/test_check_mask.py
  hyperspy/tests/signal/test_eds_tem.py
Labels: release: next patch, status: needs review, type: bug-fix

#2545 Specify file reader for hs.load
  doc/user_guide/io.rst
  hyperspy/io.py
  hyperspy/io_plugins/__init__.py
  hyperspy/tests/io/test_io.py
Labels: release: next patch, status: needs review, type: enhancement

#2555 Set reading mode hdf5 file
  doc/user_guide/io.rst
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/hspy.py
  hyperspy/io_plugins/nexus.py
  hyperspy/io_plugins/usid_hdf5.py
  hyperspy/tests/io/test_usid.py
Labels: release: next patch, status: needs review, type: bug-fix

#2554 Fix float to int casting error in estimate_shift2D
  hyperspy/_signals/signal2d.py
  hyperspy/tests/signal/test_2D_tools.py
Labels: release: next patch, status: needs review, type: bug-fix
