Repository hyperspy/hyperspy, pull requests merged in 2020-01, with the labels that each got.

#2297 Fix for dm3 reader to properly assign metadata in multi-signal files
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/tests/io/dm3_2D_data/multi_signal.dm3
  hyperspy/tests/io/test_dm3.py
Labels: release: next patch, status: needs review, type: bug-fix

#2298 Update tests following pint 0.10 release
  hyperspy/tests/axes/test_conversion_units.py
  hyperspy/tests/io/test_blockfile.py
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_tiff.py
  hyperspy/tests/signal/test_tools.py
Labels: affects: tests, release: next patch, status: needs review

#2295 Use numpy fft in fft_correlation.
  hyperspy/_signals/signal2d.py
Labels: release: next patch, status: needs review

#2300 Fix warning test suite
  hyperspy/_signals/lazy.py
  hyperspy/learn/mva.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_mva.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/mva/test_bss.py
  hyperspy/tests/mva/test_decomposition.py
  hyperspy/tests/signal/test_apodization.py
Labels: affects: tests, release: next patch, status: waiting for author

#2305 Fix travis
  .travis.yml
  hyperspy/_components/error_function.py
  hyperspy/_components/expression.py
  hyperspy/_components/skew_normal.py
  hyperspy/tests/signal/test_remove_background.py
Labels: affects: tests, release: next patch

#2165 Adding plugin to read and write to Universal Spectroscopy and Imaging Data HDF5 files
  .travis.yml
  appveyor.yml
  doc/user_guide/io.rst
  hyperspy/io_plugins/__init__.py
  hyperspy/io_plugins/usid_hdf5.py
  hyperspy/tests/io/test_usid.py
  setup.py
Labels: release: next minor, status: waiting for author, type: New feature

#2240 Serpentine scan pattern for multifit
  doc/user_guide/images/FlybackVsSerpentine.png
  doc/user_guide/model.rst
  hyperspy/axes.py
  hyperspy/model.py
  hyperspy/tests/axes/test_axes_manager.py
  hyperspy/tests/model/test_model.py
Labels: release: next minor, status: needs review, type: enhancement

#2309 Codecov
  .coveragerc
  .travis.yml
  README.rst
Labels: affects: tests, release: next patch, status: needs review, type: bug, type: bug-fix
