Repository hyperspy/hyperspy, pull requests merged in 2021-08, with the labels that each got.

#2796 Suspend plotting during fit
  doc/user_guide/eels.rst
  hyperspy/models/eelsmodel.py
  upcoming_changes/2796.bugfix.rst
Labels: status: needs review, type: bug-fix, release: next patch

#2749 Add warning to user guide saying that non-uniform axes are in beta state
  .github/workflows/tests.yml
  doc/user_guide/axes.rst
Labels: affects: documentation, status: needs review, non-uniform axis

#2791 Output size save image
  doc/user_guide/io.rst
  hyperspy/datasets/artificial_data.py
  hyperspy/io_plugins/image.py
  hyperspy/tests/io/test_image.py
  upcoming_changes/2399.new.rst
  upcoming_changes/2791.enhancements.rst
Labels: type: enhancement, status: needs review

#2775 added ValueError for unknown densities
  hyperspy/misc/material.py
  hyperspy/tests/utils/test_material.py
  upcoming_changes/2775.bugfix.rst
Labels: status: waiting for author, type: bug-fix, release: next patch
