Repository hyperspy/hyperspy, pull requests merged in 2021-01, with the labels that each got.

#2459 Generalised AxesManager iterpath
  doc/user_guide/axes.rst
  doc/user_guide/model.rst
  hyperspy/axes.py
  hyperspy/model.py
  hyperspy/tests/axes/test_axes_manager.py
  hyperspy/tests/model/test_fitting.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2620 Read EDS frame jeol
  doc/user_guide/io.rst
  hyperspy/io_plugins/jeol.py
  hyperspy/tests/io/test_jeol.py
Labels: release: next minor, status: needs review

#2615 Fix drawing multiple widgets
  CHANGES.rst
  doc/user_guide/interactive_operations_ROIs.rst
  doc/user_guide/visualisation.rst
  hyperspy/conftest.py
  hyperspy/defaults_parser.py
  hyperspy/drawing/_widgets/circle.py
  hyperspy/drawing/_widgets/horizontal_line.py
  hyperspy/drawing/_widgets/label.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/_widgets/rectangles.py
  hyperspy/drawing/_widgets/vertical_line.py
  hyperspy/drawing/figure.py
  hyperspy/drawing/marker.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/utils.py
  hyperspy/drawing/widget.py
  hyperspy/roi.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
Labels: release: next patch, status: needs review, type: bug, type: bug-fix

#2616 Fix for numpy 1.20 and set numpy>=1.16
  .github/workflows/tests.yml
  CHANGES.rst
  doc/dev_guide/testing.rst
  hyperspy/_components/gaussian.py
  hyperspy/_components/lorentzian.py
  hyperspy/_components/skew_normal.py
  hyperspy/io_plugins/protochips.py
  hyperspy/signal.py
  setup.py
Labels: release: next patch, status: needs review
