Repository hyperspy/hyperspy, pull requests merged in 2021-04, with the labels that each got.

#2694 Bruker XRF
  CHANGES.rst
  conda_environment.yml
  conda_environment_dev.yml
  hyperspy/io_plugins/bruker.py
  hyperspy/tests/io/bruker_data/bruker_m6_jetstream_file_example.spx
  hyperspy/tests/io/test_bruker.py
Labels: release: next patch, status: needs review, type: bug-fix

#2617 Improve lazy operations and Chunking
  .github/workflows/tests.yml
  CHANGES.rst
  doc/dev_guide/lazy_computations.rst
  hyperspy/_signals/hologram_image.py
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_1D_tools.py
  hyperspy/tests/signals/test_2D_tools.py
  hyperspy/tests/signals/test_find_peaks2D.py
  hyperspy/tests/signals/test_hologram_image.py
  hyperspy/tests/signals/test_lazy.py
  hyperspy/tests/signals/test_map_method.py
Labels: release: next patch, status: waiting for author, type: bug-fix

#2695 Follow up #2617
  hyperspy/_signals/lazy.py
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_map_method.py
Labels: status: needs review

#2697 EELSSpectrum: typo and style fixes in docstrings, warnings and comments
  hyperspy/_signals/eels.py
Labels: release: next patch, type: typo

#2699 Fix several typos in the documentation and comments in Signal1D
  hyperspy/_signals/signal1d.py
Labels: status: needs review, type: typo

#2709 Fix extension registration that was not working in some complex scenarions
  hyperspy/extensions.py
  setup.py
Labels: release: next patch, status: needs review

#2711 Avoid importing extensions on registration
  hyperspy/extensions.py
  setup.py
Labels: release: next patch, status: needs review

#2714 Fix latex doc build
  .github/workflows/tests.yml
Labels: affects: documentation, status: needs review

#2713 Add drone CI to test arm64
  .drone.yml
  README.rst
  hyperspy/tests/signals/test_1D_tools.py
Labels: affects: tests, status: needs review

#2722 Fix test suite with dask 2021.4.1
  azure-pipelines.yml
  hyperspy/tests/io/test_blockfile.py
Labels: affects: tests

#2721 Fix snapping
  hyperspy/axes.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
Labels: release: next patch, type: bug-fix
