Repository hyperspy/hyperspy, pull requests merged in 2021-11, with the labels that each got.

#2839 Drop python 3.6
  .github/workflows/tests.yml
  azure-pipelines.yml
  setup.py
  upcoming_changes/2839.maintenance.rst
Labels: status: needs review

#2842 Fix ragged array
  doc/user_guide/signal.rst
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/axes.py
  hyperspy/drawing/utils.py
  hyperspy/misc/slicing.py
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/tests/axes/test_axes_manager.py
  hyperspy/tests/drawing/test_plot_signal.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/signals/test_fancy_indexing.py
  hyperspy/tests/signals/test_find_peaks2D.py
  hyperspy/tests/signals/test_fourier_transform.py
  hyperspy/tests/signals/test_map_method.py
  hyperspy/tests/signals/test_ragged_signal.py
  hyperspy/tests/signals/test_transpose.py
  hyperspy/tests/test_dictionary_tree_browser.py
  upcoming_changes/2842.enhancements.rst
Labels: status: needs review, type: bug-fix, run-extension-tests

#2859 Bug fix hydrogenic gdos k edge
  hyperspy/misc/eels/hydrogenic_gos.py
  upcoming_changes/2859.bugfix.rst
Labels: type: bug-fix, release: next patch

#2852 Package impulse_data to be able to run the test suite from packages
  setup.py
Labels: status: needs review, affects: tests
