Repository hyperspy/hyperspy, pull requests merged in 2021-05, with the labels that each got.

#2724 Add docstrings to fitting functionality
  doc/user_guide/big_data.rst
  hyperspy/component.py
  hyperspy/model.py
Labels: affects: documentation, release: next patch, status: needs review

#2693 Non uniform axis updates
  doc/index.rst
  doc/user_guide/axes.rst
  doc/user_guide/getting_started.rst
  hyperspy/axes.py
  hyperspy/misc/axis_tools.py
  hyperspy/tests/axes/test_conversion_units.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/misc/test_axis_tools.py
Labels: non-uniform axis, status: needs review

#2732 Update nightly merge workflow
  .github/workflows/nightly-merge.yml
  .github/workflows/nightly-merge_non_uniform.yml
Labels: affects: tests

#2728 Fixes for binned non_uniform_axes
  hyperspy/_components/doniach.py
  hyperspy/_components/exponential.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussianhf.py
  hyperspy/_components/lorentzian.py
  hyperspy/_components/offset.py
  hyperspy/_components/pes_voigt.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/polynomial_deprecated.py
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/_components/skew_normal.py
  hyperspy/_components/split_voigt.py
  hyperspy/_components/voigt.py
  hyperspy/_signals/eds_sem.py
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/hologram_image.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/axes.py
  hyperspy/misc/utils.py
  hyperspy/models/edsmodel.py
  hyperspy/models/eelsmodel.py
  hyperspy/models/model1d.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/axes/test_axes_manager.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_doniach.py
  hyperspy/tests/component/test_exponential.py
  hyperspy/tests/component/test_gaussian.py
  hyperspy/tests/component/test_gaussianhf.py
  hyperspy/tests/component/test_lorentzian.py
  hyperspy/tests/component/test_pes_voigt.py
  hyperspy/tests/component/test_skewnormal.py
  hyperspy/tests/component/test_splitvoigt.py
  hyperspy/tests/component/test_voigt.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signals/test_remove_background.py
  hyperspy/tests/test_non-uniform_not-implemented.py
  hyperspy/tests/utils/test_stack.py
Labels: non-uniform axis, status: needs review

#2734 Fix disconnecting events when closing figure and remove_background is active
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
Labels: status: needs review, type: bug-fix

#2737 clarifications on integrate/sum for binned/non-uniform axes
  doc/user_guide/signal.rst
  hyperspy/signal.py
  hyperspy/tests/signals/test_tools.py
Labels: non-uniform axis, status: needs review

#2742 Artificialdata nonlinearaxis 2
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/axes.py
  hyperspy/datasets/artificial_data.py
  hyperspy/misc/eels/hartree_slater_gos.py
  hyperspy/misc/eels/hydrogenic_gos.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/datasets/test_artificial_data.py
Labels: non-uniform axis, status: waiting for author, type: new feature

#2750 Cleanup for the implementation of shift1D
  hyperspy/_signals/signal1d.py
Labels: release: next patch, type: enhancement

#2717 Use towncrier to generate changelog
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGES.rst
  pyproject.toml
  releasing_guide.md
  upcoming_changes/2709.enhancements.rst
  upcoming_changes/2711.enhancements.rst
  upcoming_changes/2717.maintenance.rst
  upcoming_changes/README.rst
Labels: affects: documentation, release: next patch, status: waiting for author

#2753 Move to towncrier changelog, follow up of #2717
  CHANGES.rst
  upcoming_changes/1412.new.rst
  upcoming_changes/2183.new.rst
  upcoming_changes/2386.new.rst
  upcoming_changes/2488.new.rst
  upcoming_changes/2494.enhancements.rst
  upcoming_changes/2559.enhancements.rst
  upcoming_changes/2590.enhancements.rst
  upcoming_changes/2599.new.rst
  upcoming_changes/2652.api.rst
  upcoming_changes/2688.new.rst
Labels: status: needs review

#2752 Fix is binned gui
  hyperspy/axes.py
Labels: non-uniform axis

#2744 Fix deprecation warning
  hyperspy/_components/pes_voigt.py
  hyperspy/io.py
  hyperspy/misc/example_signals_loading.py
  hyperspy/tests/drawing/test_plot_model.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/io/test_nexus_hdf.py
  hyperspy/tests/signals/data/EELS_LL_linescan_simulated_thickness_variation.hspy
  hyperspy/tests/signals/data/EELS_ZLP_linescan_simulated_thickness_variation.hspy
  hyperspy/tests/signals/test_find_peaks1D_ohaver.py
  hyperspy/tests/signals/test_map_method.py
Labels: type: bug-fix

#2747 Fix parse value string nua and fix circular import
  hyperspy/api_nogui.py
  hyperspy/axes.py
  hyperspy/datasets/artificial_data.py
  hyperspy/drawing/utils.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/utils/__init__.py
  hyperspy/utils/model_selection.py
Labels: non-uniform axis, type: bug-fix

#2743 Fix estimate_parameters for binned and non uniform axis
  hyperspy/_components/arctan.py
  hyperspy/_components/bleasdale.py
  hyperspy/_components/doniach.py
  hyperspy/_components/eels_arctan.py
  hyperspy/_components/eels_double_power_law.py
  hyperspy/_components/error_function.py
  hyperspy/_components/exponential.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussian2d.py
  hyperspy/_components/gaussianhf.py
  hyperspy/_components/heaviside.py
  hyperspy/_components/logistic.py
  hyperspy/_components/lorentzian.py
  hyperspy/_components/offset.py
  hyperspy/_components/pes_voigt.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/polynomial_deprecated.py
  hyperspy/_components/power_law.py
  hyperspy/_components/rc.py
  hyperspy/_components/skew_normal.py
  hyperspy/_components/split_voigt.py
  hyperspy/_components/voigt.py
  hyperspy/_components/volume_plasmon_drude.py
  hyperspy/axes.py
  hyperspy/component.py
  hyperspy/misc/array_tools.py
  hyperspy/signal.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/component/test_component.py
Labels: non-uniform axis

#2754 Add fix for lazy s.map and nav chunks with size of 1
  hyperspy/misc/utils.py
  hyperspy/tests/signals/test_map_method.py
Labels: release: next patch, status: needs review, type: bug-fix
