Repository hyperspy/hyperspy, pull requests merged in 2021-03, with the labels that each got.

#2644 Fix #2640
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_lazy.py
Labels: release: next patch, status: needs review, type: bug-fix

#2646 Fix future and deprecation warnings
  CHANGES.rst
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/hologram_image.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/empad.py
  hyperspy/io_plugins/nexus.py
  hyperspy/io_plugins/phenom.py
  hyperspy/io_plugins/sur.py
  hyperspy/misc/eels/hydrogenic_gos.py
  hyperspy/misc/test_utils.py
  hyperspy/misc/tv_denoise.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/misc/test_tv_denoise.py
  hyperspy/tests/signal/test_eds_tem.py
  hyperspy/tests/signal/test_hologram_image.py
  hyperspy/tests/utils/test_roi.py
  hyperspy/utils/peakfinders2D.py
Labels: release: next patch, status: needs review

#2604 Improve error message initialisation SpanROI
  CHANGES.rst
  hyperspy/misc/label_position.py
  hyperspy/roi.py
  hyperspy/tests/utils/test_roi.py
  hyperspy/ui_registry.py
  hyperspy/utils/__init__.py
Labels: release: next patch, status: needs review, type: enhancement

#2625 Fix widgets
  CHANGES.rst
  hyperspy/drawing/_widgets/circle.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/widget.py
  hyperspy/tests/drawing/plot_roi/test_plot_circle_roi_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_circle_roi_signal.png
  hyperspy/tests/drawing/plot_roi/test_plot_line2d_roi_linewidth.png
  hyperspy/tests/drawing/test_plot_roi_widgets.py
  hyperspy/tests/drawing/test_plot_widgets.py
Labels: release: next patch, status: needs review, type: bug-fix

#2624 Allow running the test suite without the pytest-mpl plugin
  CHANGES.rst
  hyperspy/conftest.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  setup.cfg
Labels: affects: tests, release: next patch, status: needs review, type: enhancement

#2658 Plot scalebar when the axis scale have different sign
  CHANGES.rst
  hyperspy/drawing/image.py
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: release: next patch, type: bug-fix

#2655 Add adjust position for SplitVoigt
  CHANGES.rst
  doc/user_guide/model.rst
  hyperspy/_components/split_voigt.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_pes_core_line_shape.py
  hyperspy/tests/component/test_pes_voigt.py
  hyperspy/tests/component/test_splitvoigt.py
Labels: release: next patch, type: bug-fix

#2654 Fix warning when using fit component and add iterpath to GUI
  CHANGES.rst
  hyperspy/models/model1d.py
Labels: release: next patch, status: needs review, type: bug-fix

#2596 Fix doc warning
  .github/workflows/tests.yml
  CHANGES.rst
  README.rst
  doc/conf.py
  doc/dev_guide/index.rst
  doc/dev_guide/intro.rst
  doc/dev_guide/testing.rst
  doc/index.rst
  doc/sphinxext/docscrape.py
  doc/sphinxext/docscrape_sphinx.py
  doc/sphinxext/gen_rst.py
  doc/sphinxext/ipython_console_highlighting.py
  doc/user_guide/cluster.rst
  doc/user_guide/getting_started.rst
  doc/user_guide/images/download_button_source.html
  doc/user_guide/images/download_hyperspy_button.png
  doc/user_guide/index.rst
  doc/user_guide/install.rst
  doc/user_guide/io.rst
  doc/user_guide/mva.rst
  doc/user_guide/signal2d.rst
  doc/user_guide/visualisation.rst
  hyperspy/_components/eels_cl_edge.py
  hyperspy/_components/gaussian2d.py
  hyperspy/_signals/eels.py
  hyperspy/axes.py
  hyperspy/component.py
  hyperspy/conftest.py
  hyperspy/docstrings/plot.py
  hyperspy/drawing/signal1d.py
  hyperspy/io_plugins/bruker.py
  hyperspy/io_plugins/nexus.py
  hyperspy/misc/eels/electron_inelastic_mean_free_path.py
  hyperspy/misc/eels/hartree_slater_gos.py
  hyperspy/misc/eels/tools.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/samfire.py
  hyperspy/samfire_utils/samfire_pool.py
  hyperspy/signal.py
  hyperspy/ui_registry.py
  hyperspy/utils/parallel_pool.py
  hyperspy/utils/peakfinders2D.py
  setup.py
Labels: affects: documentation, release: next patch, status: needs review

#2561 Save image with scalebar
  conda_environment.yml
  doc/user_guide/io.rst
  hyperspy/drawing/utils.py
  hyperspy/io_plugins/image.py
  hyperspy/tests/io/test_image.py
  setup.py
Labels: release highlight, release: next minor, status: needs review, type: New feature

#2659 Improve load documentation
  doc/user_guide/io.rst
  hyperspy/io.py
Labels: affects: documentation, release: next patch, status: needs review

#2662 Fix ambiguity in docs about ORPCA and RPCA
  doc/user_guide/mva.rst
Labels: affects: documentation, release: next patch, status: needs review

#2660 Improve error message for m.fit("Differential Evolution")
  hyperspy/model.py
Labels: release: next patch, status: needs review

#2667 Fix typos in hyperspy/drawing/image.py
  hyperspy/drawing/image.py
Labels: release: next patch, type: typo

#2671 Reduce the size of hspy v2.2 test file
  hyperspy/tests/io/hdf5_files/example2_v2.2.hspy
Labels: release: next patch, status: needs review

#2675 Fix align1D
  CHANGES.rst
  hyperspy/_signals/signal1d.py
  hyperspy/tests/signal/test_1D_tools.py
Labels: release: next patch, status: needs review, type: bug-fix

#2673 Fix finding dataset in group in EMD NCEM file
  CHANGES.rst
  hyperspy/io_plugins/emd.py
Labels: release: next patch, type: bug-fix

#2663 Add python3.9
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CHANGES.rst
  doc/dev_guide/intro.rst
  doc/dev_guide/writing_extensions.rst
  doc/index.rst
  hyperspy/_signals/eds.py
  hyperspy/drawing/_markers/vertical_line.py
  hyperspy/drawing/utils.py
  hyperspy/misc/label_position.py
  hyperspy/misc/test_utils.py
  hyperspy/tests/axes/test_conversion_units.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/io/test_fei.py
  hyperspy/tests/misc/test_test_utils.py
  hyperspy/tests/signal/test_eds_sem.py
  setup.py
Labels: affects: tests, type: enhancement

#2676 fix squeeze, add tests and improve docs
  CHANGES.rst
  doc/user_guide/signal.rst
  hyperspy/signal.py
  hyperspy/tests/signal/test_eds_tem.py
  hyperspy/tests/signal/test_tools.py
Labels: release: next patch, status: waiting for author

#2678 Ensure correct endian in numba_histogram
  hyperspy/misc/array_tools.py
  hyperspy/misc/lowess_smooth.py
  hyperspy/tests/misc/test_array_tools.py
  hyperspy/tests/signal/test_1D_tools.py
  hyperspy/tests/signal/test_3D.py
  hyperspy/tests/signal/test_linear_rebin.py
Labels: release: next patch, status: needs review

#2681 Fix CL Quant Error
  doc/user_guide/eds.rst
  hyperspy/misc/eds/utils.py
  hyperspy/tests/signal/test_eds_tem.py
Labels: release: next patch, type: bug-fix

#2685 Fix typos in widget.py
  hyperspy/drawing/widget.py
Labels: status: needs review, type: typo

#2679 Fix navigation_mask decomposition
  CHANGES.rst
  hyperspy/drawing/image.py
  hyperspy/learn/mva.py
  hyperspy/tests/drawing/test_plot_signal.py
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/learn/test_decomposition.py
Labels: release: next patch, type: bug-fix

#2684 Fix image contrast tool
  CHANGES.rst
  hyperspy/drawing/_widgets/circle.py
  hyperspy/drawing/_widgets/horizontal_line.py
  hyperspy/drawing/_widgets/label.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/_widgets/rectangles.py
  hyperspy/drawing/_widgets/vertical_line.py
  hyperspy/drawing/figure.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/widget.py
  hyperspy/extensions.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
  hyperspy/tests/drawing/test_plot_widgets.py
  hyperspy/tests/signal/test_image_contrast_editor_tool.py
Labels: release: next patch, type: bug-fix

#2683 Fix broken events when changing signal type
  hyperspy/signal.py
  hyperspy/tests/signal/test_assign_subclass.py
Labels: release: next patch, status: needs review, type: bug-fix

#2687 Minor docstrings fixes Gaussian components: typos, trailing whitespaces
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussian2d.py
  hyperspy/_components/gaussianhf.py
Labels: affects: documentation, status: needs review, type: typo

#2686 Set snap option in roi.interactive
  CHANGES.rst
  doc/user_guide/interactive_operations_ROIs.rst
  hyperspy/drawing/_widgets/range.py
  hyperspy/interactive.py
  hyperspy/roi.py
  hyperspy/tests/test_interactive.py
  hyperspy/tests/utils/test_roi.py
Labels: release: next patch, type: bug-fix, type: enhancement

#2688 Add height property to the Gaussian2D component
  CHANGES.rst
  hyperspy/_components/gaussian2d.py
  hyperspy/tests/component/test_gaussian2d.py
Labels: release: next minor, status: needs review, type: New feature

#2623 Lazy DictionaryTreeBrowser
  CHANGES.rst
  hyperspy/misc/utils.py
  hyperspy/tests/signals/__init__.py
  hyperspy/tests/signals/data/EELS_LL_linescan_simulated_thickness_variation.hspy
  hyperspy/tests/signals/data/EELS_ZLP_linescan_simulated_thickness_variation.hspy
  hyperspy/tests/signals/data/test_find_peaks1D_ohaver.hdf5
  hyperspy/tests/signals/test_1D.py
  hyperspy/tests/signals/test_1D_tools.py
  hyperspy/tests/signals/test_2D.py
  hyperspy/tests/signals/test_2D_tools.py
  hyperspy/tests/signals/test_3D.py
  hyperspy/tests/signals/test_4D.py
  hyperspy/tests/signals/test_apodization.py
  hyperspy/tests/signals/test_assign_subclass.py
  hyperspy/tests/signals/test_binned.py
  hyperspy/tests/signals/test_check_mask.py
  hyperspy/tests/signals/test_complex_signal.py
  hyperspy/tests/signals/test_complex_signal2d.py
  hyperspy/tests/signals/test_edges_range.py
  hyperspy/tests/signals/test_eds_sem.py
  hyperspy/tests/signals/test_eds_tem.py
  hyperspy/tests/signals/test_eels.py
  hyperspy/tests/signals/test_fancy_indexing.py
  hyperspy/tests/signals/test_find_peaks1D_ohaver.py
  hyperspy/tests/signals/test_find_peaks2D.py
  hyperspy/tests/signals/test_folding.py
  hyperspy/tests/signals/test_fourier_transform.py
  hyperspy/tests/signals/test_hologram_image.py
  hyperspy/tests/signals/test_hologram_image_statistics.py
  hyperspy/tests/signals/test_image.py
  hyperspy/tests/signals/test_image_contrast_editor_tool.py
  hyperspy/tests/signals/test_inheritance.py
  hyperspy/tests/signals/test_kramers_kronig_transform.py
  hyperspy/tests/signals/test_lazy.py
  hyperspy/tests/signals/test_lazy_tools.py
  hyperspy/tests/signals/test_linear_rebin.py
  hyperspy/tests/signals/test_map_method.py
  hyperspy/tests/signals/test_remove_background.py
  hyperspy/tests/signals/test_rgb.py
  hyperspy/tests/signals/test_signal_operators.py
  hyperspy/tests/signals/test_signal_subclass_conversion.py
  hyperspy/tests/signals/test_spectrum.py
  hyperspy/tests/signals/test_spike_removal_tool.py
  hyperspy/tests/signals/test_tools.py
  hyperspy/tests/signals/test_transpose.py
  hyperspy/tests/test_dictionary_tree_browser.py
  setup.py
Labels: release: next patch, status: needs review, type: enhancement

#2690 Fix setting offset in rebin: the offset was changed in the wrong axis.
  CHANGES.rst
  hyperspy/signal.py
  hyperspy/tests/signals/test_linear_rebin.py
Labels: release: next patch, status: needs review, type: bug-fix
