Repository hyperspy/hyperspy, pull requests merged in 2021-07, with the labels that each got.

#2765 value2index: convert index to int
  hyperspy/axes.py
  hyperspy/misc/array_tools.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/misc/test_array_tools.py
  hyperspy/tests/utils/test_roi.py
Labels: non-uniform axis, status: needs review, type: bug-fix

#2790 Handle polynomial with order >10 for estimate_parameters
  hyperspy/_components/polynomial.py
  hyperspy/tests/component/test_components.py
  upcoming_changes/2790.bugfix.rst
Labels: release: next patch, status: waiting for author, type: bug-fix

#2793 Update minimal requirement of importlib_metadata to 3.6
  setup.py
  upcoming_changes/2793.bugfix.rst
Labels: release: next patch, type: bug-fix

#2802 Check if plot is not active in add marker() before plotting (bugfix)
  .gitignore
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_markers.py
  upcoming_changes/2799.bugfix.rst
Labels: release: next patch, type: bug-fix

#2795 Add context manager to switch iterpath
  doc/user_guide/axes.rst
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/axes.py
  hyperspy/datasets/artificial_data.py
  hyperspy/signal.py
  hyperspy/tests/axes/test_axes_manager.py
  hyperspy/tests/signals/test_1D_tools.py
  hyperspy/tests/signals/test_find_peaks2D.py
  upcoming_changes/2795.enhancements.rst
Labels: status: needs review, type: enhancement
