Repository hyperspy/hyperspy, pull requests merged in 2021-02, with the labels that each got.

#2341 Default values for ROIs
  doc/user_guide/interactive_operations_ROIs.rst
  hyperspy/roi.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/utils/test_roi.py
Labels: release: next minor, status: waiting for author, type: enhancement

#2608 Fix warning when reading STEM images acquired with Digiscan
  hyperspy/io.py
  hyperspy/io_plugins/digital_micrograph.py
  hyperspy/tests/signal/test_assign_subclass.py
Labels: release: next patch, status: needs review, type: bug-fix

#2597 Improve error message when loading file.
  CHANGES.rst
  hyperspy/io.py
  hyperspy/tests/io/test_io.py
Labels: release: next patch, status: needs review, type: enhancement

#2621 Add update instructions
  CHANGES.rst
  doc/user_guide/install.rst
Labels: affects: documentation, release: next patch, status: needs review, type: enhancement

#2631 Compute navigator for lazy signal
  .github/workflows/tests.yml
  CHANGES.rst
  doc/user_guide/big_data.rst
  doc/user_guide/visualisation.rst
  hyperspy/_signals/lazy.py
  hyperspy/docstrings/plot.py
  hyperspy/io_plugins/hspy.py
  hyperspy/misc/array_tools.py
  hyperspy/misc/test_utils.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/drawing/test_plot_lazy.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/drawing/test_plot_signal.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/misc/test_array_tools.py
Labels: release: next minor, status: needs review, type: bug-fix, type: enhancement

#2629 Use dask chunks when saving lazy signal
  CHANGES.rst
  doc/user_guide/io.rst
  hyperspy/io_plugins/emd.py
  hyperspy/io_plugins/hspy.py
  hyperspy/signal.py
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_hdf5.py
Labels: release: next patch, status: needs review, type: bug-fix

#2645 Use 'dask_auto' when rechunk=True in change_dtype.
  CHANGES.rst
  hyperspy/_signals/lazy.py
  hyperspy/tests/signal/test_lazy_tools.py
Labels: release: next patch, status: needs review, type: bug-fix

#2649 Non-uniform-axes - fix attributes in axes type conversion
  hyperspy/axes.py
  hyperspy/tests/axes/test_data_axis.py
Labels: non-linear axis

#2647 Changing regrex to dictionary look up
  CHANGES.rst
  hyperspy/signal_tools.py
  hyperspy/tests/signal/test_find_peaks2D.py
  hyperspy/utils/peakfinders2D.py
Labels: affects: hyperspy_gui_ipywidgets, affects: hyperspy_gui_traitsui, release: next patch, status: waiting for author, type: bug-fix
