Repository hyperspy/hyperspy, pull requests merged in 2022-10, with the labels that each got.

#3045 Simplify API import remove markers aliases
  CHANGES.rst
  doc/user_guide/visualisation.rst
  hyperspy/_signals/eds.py
  hyperspy/api_nogui.py
  hyperspy/datasets/__init__.py
  hyperspy/datasets/artificial_data.py
  hyperspy/datasets/example_signals.py
  hyperspy/misc/label_position.py
  hyperspy/samfire_utils/fit_tests.py
  hyperspy/samfire_utils/global_strategies.py
  hyperspy/samfire_utils/local_strategies.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/test_import.py
  hyperspy/utils/markers.py
  hyperspy/utils/plot.py
  hyperspy/utils/samfire.py
Labels: type: API change, status: waiting for author

#3038 Add development branch of RosettaSciIO in `setup.py`
  .drone.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  azure-pipelines.yml
  setup.py
Labels: status: needs review

#3052 Fix pint import with pint>=0.20
  hyperspy/misc/axis_tools.py
  upcoming_changes/3052.bugfix.rst
Labels: type: bug-fix, run-extension-tests
