Repository hyperspy/hyperspy, pull requests merged in 2022-08, with the labels that each got.

#2981 Fix for dask 2022.7.1
  azure-pipelines.yml
  hyperspy/_signals/hologram_image.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_map_method.py
  upcoming_changes/2981.bugfix.rst
Labels: status: needs review, type: bug-fix, run-extension-tests

#2984 Fix time zone test windows
  hyperspy/signal_tools.py
  hyperspy/tests/misc/test_date_time_tools.py
  upcoming_changes/2984.maintenance.rst
Labels: affects: tests

#2995 Tweak display x-rays line when using log norm and the line intensity is 0
  hyperspy/_signals/eds.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/signals/test_eds_tem.py
  upcoming_changes/2995.bugfix.rst
Labels: status: needs review

#2977 Revised lgtm code consolidation
  hyperspy/_components/expression.py
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/axes.py
  hyperspy/component.py
  hyperspy/drawing/_widgets/circle.py
  hyperspy/drawing/_widgets/horizontal_line.py
  hyperspy/drawing/_widgets/label.py
  hyperspy/drawing/_widgets/line2d.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/_widgets/rectangles.py
  hyperspy/drawing/_widgets/vertical_line.py
  hyperspy/drawing/image.py
  hyperspy/drawing/utils.py
  hyperspy/misc/array_tools.py
  hyperspy/misc/axis_tools.py
  hyperspy/misc/eds/utils.py
  hyperspy/misc/ipython_tools.py
  hyperspy/misc/model_tools.py
  hyperspy/misc/utils.py
  hyperspy/signal.py
  release_debian
  upcoming_changes/2977.bugfix.rst
Labels: status: needs review, type: bug-fix

#3002 Changelog rsciio deprecation
  CHANGES.rst
Labels: status: needs review

#3003 Pin towncrier
  setup.py
Labels: status: needs review, type: maintenance
