Repository hyperspy/hyperspy, pull requests merged in 2022-09, with the labels that each got.

#3005 Fix handling constant derivative in `spikes_removal_tools`
  hyperspy/_signals/signal1d.py
  hyperspy/signal_tools.py
  hyperspy/tests/signals/test_eels.py
  hyperspy/tests/signals/test_spike_removal_tool.py
  upcoming_changes/3005.bugfix.rst
Labels: type: bug-fix, release: next patch

#2998 Remove deprecation - Axes, IO, Model
  CHANGES.rst
  azure-pipelines.yml
  doc/user_guide/axes.rst
  doc/user_guide/big_data.rst
  doc/user_guide/io.rst
  doc/user_guide/model.rst
  hyperspy/axes.py
  hyperspy/io.py
  hyperspy/misc/utils.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/signal.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_components2D.py
  hyperspy/tests/component/test_gaussianhf.py
  hyperspy/tests/model/test_edsmodel.py
  hyperspy/tests/model/test_fit_component.py
  hyperspy/tests/model/test_fitting.py
  hyperspy/tests/model/test_linear_model.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/samfire/test_goodness_of_fit_tests.py
  hyperspy/tests/signals/test_assign_subclass.py
  hyperspy/tests/utils/test_stack.py
Labels: release: next major, type: maintenance

#2999 Remove deprecation - MVA
  CHANGES.rst
  doc/user_guide/mva.rst
  hyperspy/learn/mva.py
  hyperspy/learn/rpca.py
  hyperspy/learn/svd_pca.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/learn/test_rpca.py
Labels: release: next major, type: maintenance

#3000 Remove deprecation - Drawing
  CHANGES.rst
  hyperspy/_signals/complex_signal2d.py
  hyperspy/_signals/signal2d.py
  hyperspy/conftest.py
  hyperspy/defaults_parser.py
  hyperspy/docstrings/plot.py
  hyperspy/drawing/image.py
  hyperspy/drawing/signal1d.py
  hyperspy/drawing/utils.py
  hyperspy/tests/doc_docstr_examples/doc_examples_Visualisation.ipynb
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: status: needs review, release: next major, type: maintenance

#3007 Remove deprecated `binned` metadata
  .gitignore
  CHANGES.rst
  hyperspy/_components/doniach.py
  hyperspy/_components/exponential.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussianhf.py
  hyperspy/_components/lorentzian.py
  hyperspy/_components/offset.py
  hyperspy/_components/pes_voigt.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/polynomial_deprecated.py
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/_components/skew_normal.py
  hyperspy/_components/split_voigt.py
  hyperspy/_components/voigt.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/component.py
  hyperspy/misc/utils.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/misc/test_dictionary_tree_browser.py
  hyperspy/tests/misc/test_utils.py
  hyperspy/tests/model/test_fitting.py
  hyperspy/tests/model/test_linear_model.py
Labels: status: needs review, release: next major, type: maintenance

#3016 Fix SpanSelector for matplotlib 3.6
  hyperspy/drawing/_widgets/range.py
  upcoming_changes/3016.maintenance.rst
Labels: status: needs review, type: bug-fix

#3009 compatibility of io with format_alias defined in rsciio
  hyperspy/io.py
  hyperspy/tests/test_io.py
  upcoming_changes/3009.api.rst
Labels: status: needs review, type: maintenance

#3008 Fix removing horizontal and vertical line widget
  hyperspy/drawing/_widgets/horizontal_line.py
  hyperspy/drawing/_widgets/vertical_line.py
  hyperspy/drawing/widget.py
  hyperspy/tests/drawing/test_widget.py
  upcoming_changes/3008.bugfix.rst
Labels: status: needs review, type: bug-fix

#3017 Remove Signal deprecation
  CHANGES.rst
  doc/user_guide/getting_started.rst
  hyperspy/_signals/lazy.py
  hyperspy/defaults_parser.py
  hyperspy/interactive.py
  hyperspy/learn/mva.py
  hyperspy/misc/utils.py
  hyperspy/samfire.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/learn/test_decomposition.py
  hyperspy/tests/learn/test_lazy_decomposition.py
  hyperspy/tests/misc/test_dictionary_tree_browser.py
  hyperspy/tests/samfire/test_samfire.py
  hyperspy/tests/signals/test_lazy.py
  hyperspy/ui_registry.py
Labels: status: needs review

#3020 Remove deprecated navigator keys
  CHANGES.rst
  hyperspy/axes.py
Labels: status: needs review

#3019 Fix drone CI
  .drone.yml
Labels: status: needs review

#3033 Fix error handling when trying to convert a ragged signal to non-ragged
  hyperspy/signal.py
  upcoming_changes/3033.maintenance..rst
Labels: status: needs review, type: maintenance

#3032 Fix deprecated import of scipy `ascent`
  hyperspy/drawing/_markers/arrow.py
  hyperspy/drawing/_markers/ellipse.py
  hyperspy/drawing/_markers/point.py
  hyperspy/drawing/_markers/rectangle.py
  hyperspy/misc/tv_denoise.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_markers.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/misc/test_tv_denoise.py
  hyperspy/tests/signals/test_2D_tools.py
  hyperspy/utils/markers.py
  upcoming_changes/3032.maintenance.rst
Labels: type: maintenance

#3035 Fix link to example of numpydoc
  doc/dev_guide/writing_docs.rst
Labels: affects: documentation, status: needs review

#3036 Change order import to avoid deprecation warning
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/signals/test_2D_tools.py
Labels: status: needs review
