Repository hyperspy/hyperspy, pull requests merged in 2022-06, with the labels that each got.

#2952 Fix triggering event range widget
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/signal1d.py
  hyperspy/interactive.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
  hyperspy/tests/drawing/test_plot_signal.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  upcoming_changes/2952.bugfix.rst
Labels: status: needs review, type: bug-fix

#2948 Fix interactive `set_signal_range` model
  hyperspy/models/model1d.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
  upcoming_changes/2946.bugfix.rst
  upcoming_changes/2948.bugfix.rst
Labels: status: needs review, type: bug-fix

#2957 Fix signal API documentation
  hyperspy/_signals/dielectric_function.py
  hyperspy/_signals/eds.py
  hyperspy/_signals/eds_sem.py
  hyperspy/_signals/eds_tem.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  upcoming_changes/2957.bugfix.rst
Labels: affects: documentation, status: needs review, type: bug-fix, release: next patch

#2868 Refactor of elements.py and test for the Hartree Slater cross sections.
  hyperspy/misc/eels/base_gos.py
  hyperspy/misc/eels/hartree_slater_gos.py
  hyperspy/misc/elements.py
  upcoming_changes/2868.maintenance.rst
Labels: type: enhancement, status: needs review, release: next minor

#2960 Fix packaging and regression introduced in #2868
  hyperspy/misc/eels/base_gos.py
  hyperspy/misc/eels/hartree_slater_gos.py
  setup.py
  upcoming_changes/2954.bugfix.rst
Labels: status: waiting for author, type: bug-fix, release: next patch

#2961 Fix estimate_shift2d and align2d docstrings
  doc/user_guide/interactive_operations_ROIs.rst
  hyperspy/_signals/signal2d.py
  upcoming_changes/2961.doc.rst
Labels: type: bug, affects: documentation, status: needs review, type: bug-fix, release: next patch

#2964 Fix masked norm poisson
  hyperspy/learn/mva.py
  hyperspy/tests/learn/test_decomposition.py
  upcoming_changes/2964.bugfix.rst
Labels: type: bug, status: needs review, type: bug-fix, release: next patch
