Repository hyperspy/hyperspy, pull requests merged in 2022-04, with the labels that each got.

#2874 Add file reading metadata to Signals
  .gitignore
  doc/user_guide/metadata_structure.rst
  hyperspy/io.py
  hyperspy/tests/io/test_blockfile.py
  hyperspy/tests/io/test_bruker.py
  hyperspy/tests/io/test_dm3.py
  hyperspy/tests/io/test_emd.py
  hyperspy/tests/io/test_hdf5.py
  hyperspy/tests/io/test_io.py
  hyperspy/tests/io/test_jeol.py
  hyperspy/tests/io/test_mrcz.py
  hyperspy/tests/io/test_msa.py
  hyperspy/tests/io/test_nexus_hdf.py
  hyperspy/tests/io/test_tiff.py
  upcoming_changes/2873.enhancements.rst
Labels: type: enhancement, affects: documentation, status: needs review, release: next minor, affects: tests

#2918 Fixed spikes_removal_tool bug when no navigator is present
  hyperspy/signal_tools.py
  hyperspy/tests/signals/test_spike_removal_tool.py
  upcoming_changes/2918.bugfix.rst
Labels: type: bug-fix

#2915 Bugfixes, docstring improvements and add several unit tests for EELSModel class, version 2
  hyperspy/models/eelsmodel.py
  hyperspy/tests/model/test_eelsmodel.py
Labels: status: needs review, type: bug-fix, release: next minor, affects: tests

#2916 Fix eelsdb
  hyperspy/io_plugins/msa.py
  hyperspy/misc/eels/eelsdb.py
  hyperspy/tests/datasets/test_eelsdb.py
  upcoming_changes/2916.bugfix.rst
Labels: status: needs review, type: bug-fix

#2921 Fix passing keyword argument to ridge_regression
  hyperspy/model.py
  hyperspy/tests/model/test_linear_model.py
Labels: status: needs review, type: bug-fix

#2919 Fix jeol API docs and privatise module function
  hyperspy/axes.py
  hyperspy/io_plugins/jeol.py
Labels: affects: documentation, type: bug-fix

#2822 Bugfix for cliff-lorimer quantification
  hyperspy/_signals/eds_tem.py
  hyperspy/misc/eds/utils.py
  hyperspy/tests/signals/test_eds_tem.py
  upcoming_changes/2822.bugfix.rst
Labels: type: bug-fix, release: next patch

#2925 Fix packaging vendored matplotlib widgets
  setup.py
Labels: status: needs review

#2830 Protect axes manager attribute
  hyperspy/_signals/complex_signal1d.py
  hyperspy/_signals/complex_signal2d.py
  hyperspy/_signals/eds.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/axes.py
  hyperspy/io.py
  hyperspy/models/edsmodel.py
  hyperspy/signal.py
  hyperspy/signal_tools.py
  hyperspy/tests/doc_docstr_examples/doc_examples_Visualisation.ipynb
  hyperspy/tests/drawing/test_plot_mva.py
  hyperspy/tests/io/test_ripple.py
  hyperspy/tests/model/test_eelsmodel.py
  hyperspy/tests/signals/test_assign_subclass.py
  hyperspy/tests/signals/test_complex_signal.py
  hyperspy/tests/signals/test_fancy_indexing.py
  hyperspy/tests/signals/test_map_method.py
  hyperspy/tests/signals/test_ragged_signal.py
  hyperspy/tests/signals/test_transpose.py
  hyperspy/tests/utils/test_stack.py
  upcoming_changes/2830.deprecation.rst
  upcoming_changes/2864.bugfix.rst
  upcoming_changes/2878.bugfix.rst
  upcoming_changes/2898.bugfix.rst
  upcoming_changes/2903.bugfix.rst
  upcoming_changes/2910.api.rst
Labels: release: next minor, run-extension-tests

#2928 add new issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: status: needs review

#1791 Interactive calibration for Signal2D
  doc/user_guide/signal2d.rst
  hyperspy/_signals/signal2d.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/signal_tools.py
  hyperspy/tests/signals/test_2D_tools.py
  upcoming_changes/1791.new.rst
Labels: status: needs review, type: new feature, release: next minor

#2930 Signal tool fixes
  hyperspy/misc/label_position.py
  hyperspy/signal_tools.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
Labels: status: needs review, type: bug-fix

#2931 Fix overlay plot image
  conda_environment_dev.yml
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-auto-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-auto-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-colors1-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_1.0-colors1-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-auto-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-auto-label1-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-colors1-auto-all.png
  hyperspy/tests/drawing/plot_signal2d/test_plot_overlay_alphas1-colors1-label1-all.png
  hyperspy/tests/drawing/test_plot_signal2d.py
Labels: status: needs review, type: bug-fix

#2908 Support for Hamamatsu Streak tiff metadata
  doc/user_guide/io.rst
  hyperspy/io_plugins/sur.py
  hyperspy/io_plugins/tiff.py
  hyperspy/tests/io/test_tiff.py
  hyperspy/tests/io/tiff_files/tiff_hamamatsu.zip
  upcoming_changes/2908.new.rst
Labels: status: needs review
