Repository hyperspy/hyperspy, pull requests merged in 2022-11, with the labels that each got.

#3062 Fix `plot_spectra` legend for "cascade" style
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal1d.py
Labels: type: bug, status: needs review, type: bug-fix, release: next patch

#3064 Add a section on the git history to git.rst
  doc/dev_guide/git.rst
  upcoming_changes/3064.doc.rst
Labels: affects: documentation

#3037 Deprecation removal
  CHANGES.rst
  hyperspy/component.py
  hyperspy/signal.py
  hyperspy/tests/model/test_model_as_dictionary.py
  hyperspy/tests/model/test_parameter.py
  hyperspy/tests/signals/test_assign_subclass.py
Labels: status: needs review
