Repository hyperspy/hyperspy, pull requests merged in 2022-02, with the labels that each got.

#2879 Corrected some typos in the development guide
  doc/dev_guide/coding_style.rst
  doc/dev_guide/git.rst
  doc/dev_guide/lazy_computations.rst
  doc/dev_guide/speeding_up_code.rst
  doc/dev_guide/testing.rst
  doc/dev_guide/useful_information.rst
  doc/dev_guide/writing_docs.rst
  doc/dev_guide/writing_extensions.rst
Labels: status: needs review

#2883 Fix errors due to deprecation of scipy.ndimage.filters namespace
  hyperspy/_signals/signal1d.py
Labels: status: needs review

#2884 Remove scipy deprecated namespaces
  hyperspy/_signals/eds_tem.py
  hyperspy/utils/peakfinders2D.py
Labels: status: needs review

#2887 Exclude ipython 8.0.* instead of 8.0
  conda_environment.yml
  setup.py
Labels: status: needs review, release: next patch

#2888 Fix failing test due to changes in dask.keys keyword
  hyperspy/_signals/lazy.py
Labels: type: bug, status: needs review

#2889 Fix test_blockfile unit test, due to change in dask keyword naming
  hyperspy/tests/io/test_blockfile.py
Labels: status: needs review, type: bug-fix, affects: tests

#2890 Remove use of remaining deprecated scipy namespaces
  hyperspy/utils/peakfinders2D.py
Labels: status: needs review

#2891 Merge RELEASE_next_patch into RELEASE_next_minor
  hyperspy/utils/peakfinders2D.py
Labels: status: needs review

#2893 Update links
  doc/dev_guide/writing_docs.rst
  doc/user_guide/eds.rst
  hyperspy/drawing/utils.py
Labels: affects: documentation, status: needs review

#2633 Add functions to search DictionaryTreeBrowser (e.g. metadata)
  doc/user_guide/metadata_structure.rst
  hyperspy/misc/test_utils.py
  hyperspy/misc/utils.py
  hyperspy/tests/misc/test_dictionary_tree_browser.py
  hyperspy/tests/misc/test_utils.py
  hyperspy/tests/test_dictionary_tree_browser.py
  upcoming_changes/2633.enhancements.rst
Labels: type: enhancement, affects: documentation, status: needs review, release: next minor, affects: tests
