Repository hyperspy/hyperspy, pull requests merged in 2023-11, with the labels that each got.

#3251 Pin pillow to <10.1
  conda_environment.yml
  setup.py
  upcoming_changes/3251.maintenance.rst
Labels: status: needs review

#3197 Rename crop image
  doc/user_guide/signal1d.rst
  doc/user_guide/signal2d.rst
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/tests/signals/test_2D.py
  upcoming_changes/3197.api.rst
Labels: status: needs review

#3252 Add support for pep 660 editable installs in extension
  hyperspy/extensions.py
  upcoming_changes/3252.enhancements.rst
Labels: status: needs review

#3253 Rename datasets to data and tidy up submodule
  doc/conf.py
  doc/reference/api.data.rst
  doc/reference/api.datasets/artificial_data.rst
  doc/reference/api.datasets/index.rst
  doc/reference/index.rst
  examples/region_of_interest/SpanROI.py
  examples/region_of_interest/SpanROI_interactive_sum.py
  hyperspy/_signals/complex_signal.py
  hyperspy/api_nogui.py
  hyperspy/data/__init__.py
  hyperspy/data/artificial_data.py
  hyperspy/data/two_gaussians.py
  hyperspy/signal.py
  hyperspy/tests/datasets/__init__.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/model/test_linear_model.py
  hyperspy/tests/test_data.py
  hyperspy/tests/test_import.py
  setup.py
  upcoming_changes/3253.api.rst
Labels: release: next major

#3255 HyperSpy on pyodide (and jupyterlite)
  .github/workflows/build.yml
  doc/user_guide/install.rst
  hyperspy/_components/bleasdale.py
  hyperspy/_components/exponential.py
  hyperspy/_components/expression.py
  hyperspy/_components/gaussian.py
  hyperspy/_components/gaussian2d.py
  hyperspy/_components/gaussianhf.py
  hyperspy/_components/logistic.py
  hyperspy/_components/lorentzian.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/power_law.py
  hyperspy/_components/rc.py
  hyperspy/_signals/lazy.py
  hyperspy/component.py
  hyperspy/conftest.py
  hyperspy/decorators.py
  hyperspy/misc/array_tools.py
  hyperspy/misc/eds/__init__.py
  hyperspy/misc/export_dictionary.py
  hyperspy/misc/holography/__init__.py
  hyperspy/misc/holography/example_signals/00_ref_Vbp_130V_0V_bin2_crop.hdf5
  hyperspy/misc/holography/example_signals/01_holo_Vbp_130V_0V_bin2_crop.hdf5
  hyperspy/misc/lowess_smooth.py
  hyperspy/model.py
  hyperspy/samfire.py
  hyperspy/samfire_utils/samfire_kernel.py
  hyperspy/samfire_utils/samfire_worker.py
  hyperspy/tests/component/test_backcompatibility.py
  hyperspy/tests/component/test_bleasdale.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/drawing/data/signal_markers_hs1_7_5.hspy
  hyperspy/tests/drawing/test_markers.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/samfire/test_samfire.py
  hyperspy/tests/signals/test_find_peaks1D_ohaver.py
  hyperspy/utils/peakfinders2D.py
  setup.py
  upcoming_changes/3255.enhancements.rst
Labels: status: needs review, run-packaging

#3258 Fix the "flyback" to "serpentine" deprecation
  hyperspy/_signals/signal1d.py
  hyperspy/axes.py
  hyperspy/drawing/utils.py
  hyperspy/tests/component/test_gaussianhf.py
Labels: status: needs review

#3260 Install the rsciio hdf5 extra
  setup.py
Labels: status: needs review, release: next major

#3256 Python3.12
  .github/workflows/tests.yml
  setup.py
  upcoming_changes/3256.maintenance.rst
Labels: status: needs review, type: maintenance

#3244 Fix setting bounds for trf, dogbox optimizer
  hyperspy/model.py
  hyperspy/tests/model/test_fitting.py
  upcoming_changes/3244.bugfix.rst
Labels: status: needs review, type: bug-fix
