Repository hyperspy/hyperspy, pull requests merged in 2023-03, with the labels that each got.

#3073 Add support for Phenom .elid revision 3 and 4 formats
  hyperspy/io_plugins/phenom.py
  hyperspy/tests/io/phenom_data/Elid2Version3.elid
  hyperspy/tests/io/phenom_data/Elid2Version4.elid
  hyperspy/tests/io/test_phenom.py
  upcoming_changes/3073.enhancements.rst
Labels: type: enhancement

#3096 Fix external reference (rosettasciio) in documentation
  CHANGES.rst
Labels: affects: documentation

#3108 Fix linkchecker documentation
  doc/conf.py
  doc/user_guide/bibliography.rst
  doc/user_guide/model.rst
  hyperspy/misc/eds/ffast_mac.py
  hyperspy/misc/eels/electron_inelastic_mean_free_path.py
  hyperspy/misc/material.py
  upcoming_changes/3108.maintenance.rst
Labels: affects: documentation, release: next patch, type: maintenance

#3109 Speed up `to_numpy` to fix fitting slowdown
  .gitignore
  hyperspy/misc/utils.py
  hyperspy/tests/misc/test_utils.py
  upcoming_changes/3109.bugfix.rst
Labels: type: regression, status: needs review, type: bug-fix, release: next patch

#3118 Fix plotting boolean array with `hs.plot.plot_images`
  .github/workflows/tests.yml
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  setup.py
  upcoming_changes/3118.bugfix.rst
Labels: type: bug-fix
