Repository hyperspy/hyperspy, pull requests merged in 2023-09, with the labels that each got.

#3204 s.find_peaks docstring: fix reference to wrong function
  hyperspy/_signals/signal2d.py
Labels: status: needs review, release: next major

#3222 Fix resizers
  hyperspy/drawing/widget.py
  hyperspy/misc/test_utils.py
  hyperspy/tests/drawing/plot_roi/test_plot_circle_roi_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_circle_roi_signal.png
  hyperspy/tests/drawing/plot_roi/test_plot_rectangular_roi_navigation.png
  hyperspy/tests/drawing/plot_roi/test_plot_rectangular_roi_signal.png
  hyperspy/tests/drawing/test_plot_widgets.py
  hyperspy/tests/drawing/test_widget.py
  upcoming_changes/3222.bugfix.rst
Labels: type: bug-fix

#3216 Expand documentation on extensions
  doc/intro.rst
  doc/user_guide/io.rst
  doc/user_guide/signal/signal_basics.rst
Labels: affects: documentation

#3221 Add example interactive roi
  examples/region_of_interest/README.rst
  examples/region_of_interest/SpanROI.py
  examples/region_of_interest/SpanROI_interactive_sum.py
  hyperspy/roi.py
  hyperspy/tests/utils/test_roi.py
  upcoming_changes/3221.enhancements.rst
Labels: type: enhancement, status: needs review

#3219 plot_spectra heatmap should take kwarg as well
  hyperspy/drawing/utils.py
  upcoming_changes/3219.enhancements.rst
Labels: type: enhancement, status: waiting for author

#3225 Scipy deprecation
  doc/user_guide/region_of_interest.rst
  doc/user_guide/signal/generic_tools.rst
  doc/user_guide/visualisation.rst
  hyperspy/tests/doc_docstr_examples/doc_examples_Visualisation.ipynb
  upcoming_changes/3225.maintenance.rst
Labels: affects: documentation, status: needs review

#3198 Map Clean Up
  doc/user_guide/big_data.rst
  doc/user_guide/signal/generic_tools.rst
  doc/user_guide/signal2d.rst
  hyperspy/_signals/complex_signal.py
  hyperspy/_signals/eels.py
  hyperspy/_signals/signal1d.py
  hyperspy/_signals/signal2d.py
  hyperspy/conftest.py
  hyperspy/defaults_parser.py
  hyperspy/docstrings/signal.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_1D_tools.py
  hyperspy/tests/signals/test_complex_signal.py
  hyperspy/tests/signals/test_cuda.py
  hyperspy/tests/signals/test_find_peaks2D.py
  hyperspy/tests/signals/test_map_method.py
  setup.py
  upcoming_changes/3198.api.rst
Labels: type: API change

#3206 EELS functional fine structure
  doc/user_guide/eels.rst
  doc/user_guide/images/EELS_BN_B_zoomin.png
  doc/user_guide/images/EELS_BN_B_zoomin_with_gaussians.png
  hyperspy/_components/eels_cl_edge.py
  hyperspy/models/eelsmodel.py
  hyperspy/tests/model/test_eelsmodel.py
  upcoming_changes/3206.new.rst
Labels: status: needs review, type: new feature, release: next minor

#3173 Pretty logging
  hyperspy/logger.py
  upcoming_changes/3173.new.rst
Labels: status: waiting for author
