Repository hyperspy/hyperspy, pull requests merged in 2023-01, with the labels that each got.

#3079 Add pooch as test dependency - required to use scipy.dataset
  conda_environment_dev.yml
  hyperspy/signal.py
  hyperspy/tests/drawing/test_plot_roi_widgets.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  setup.py
  upcoming_changes/3079.maintenance.rst
Labels: status: needs review

#3084 Replace imgmath by mathjax sphinx-extension
  doc/conf.py
  upcoming_changes/3084.doc.rst
Labels: affects: documentation, status: needs review

#3085 Add documentation labels
  CHANGES.rst
  doc/user_guide/axes.rst
  doc/user_guide/basic_usage.rst
  doc/user_guide/bibliography.rst
  doc/user_guide/dielectric_function.rst
  doc/user_guide/eels.rst
  doc/user_guide/model/adding_components.rst
  doc/user_guide/model/creating_model.rst
  doc/user_guide/model/model_components.rst
  doc/user_guide/model/model_parameters.rst
  doc/user_guide/mva/export_results.rst
  doc/user_guide/signal/basic_statistical_analysis.rst
  doc/user_guide/signal/generic_tools.rst
  doc/user_guide/signal/index.rst
  doc/user_guide/signal1d.rst
  doc/user_guide/signal2d.rst
Labels: affects: documentation

#3088 Fix linkchecker documentation
  doc/conf.py
Labels: affects: documentation

#3089 Rsciio API change
  hyperspy/tests/test_io.py
Labels: status: needs review, affects: tests
