Repository hyperspy/hyperspy, pull requests merged in 2023-05, with the labels that each got.

#3124 Fix test with scipy1.11 and update deprecated `scipy.interpolate.interp2d`
  hyperspy/signal.py
  hyperspy/tests/misc/test_utils.py
  hyperspy/tests/signals/test_hologram_image.py
  hyperspy/tests/signals/test_map_method.py
  upcoming_changes/3124.bugfix.rst
Labels: status: needs review, type: maintenance

#3144 Drop python 3.7
  .github/workflows/release.yml
  .github/workflows/tests.yml
  azure-pipelines.yml
  conda_environment.yml
  hyperspy/_components/error_function.py
  hyperspy/_components/power_law.py
  hyperspy/_components/skew_normal.py
  hyperspy/_components/voigt.py
  hyperspy/_signals/lazy.py
  hyperspy/learn/mva.py
  hyperspy/learn/svd_pca.py
  hyperspy/misc/utils.py
  hyperspy/model.py
  hyperspy/signal.py
  hyperspy/tests/component/test_erf.py
  hyperspy/tests/component/test_skewnormal.py
  hyperspy/tests/learn/test_svd_pca.py
  hyperspy/tests/misc/test_tv_denoise.py
  hyperspy/tests/model/test_fitting.py
  hyperspy/tests/signals/test_2D_tools.py
  hyperspy/tests/signals/test_cuda.py
  setup.cfg
  setup.py
  upcoming_changes/3050.maintenance.rst
  upcoming_changes/3144.maintenance.rst
Labels: status: needs review, type: maintenance

#3142 Find peaks2d refactor
  CHANGES.rst
  hyperspy/_signals/signal2d.py
  hyperspy/tests/signals/test_find_peaks2D.py
  hyperspy/utils/peakfinders2D.py
  upcoming_changes/3142.new.rst
Labels: type: enhancement, status: needs review, type: API change

#3063 Remove deprecated components and legacy options
  CHANGES.rst
  doc/user_guide/model/fitting_model.rst
  doc/user_guide/mva/decomposition.rst
  hyperspy/_components/arctan.py
  hyperspy/_components/eels_arctan.py
  hyperspy/_components/pes_voigt.py
  hyperspy/_components/polynomial.py
  hyperspy/_components/polynomial_deprecated.py
  hyperspy/_components/voigt.py
  hyperspy/component.py
  hyperspy/components1d.py
  hyperspy/drawing/_markers/arrow.py
  hyperspy/drawing/_markers/ellipse.py
  hyperspy/drawing/_markers/horizontal_line.py
  hyperspy/drawing/_markers/horizontal_line_segment.py
  hyperspy/drawing/_markers/line_segment.py
  hyperspy/drawing/_markers/point.py
  hyperspy/drawing/_markers/rectangle.py
  hyperspy/drawing/_markers/text.py
  hyperspy/drawing/_markers/vertical_line.py
  hyperspy/drawing/_markers/vertical_line_segment.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/misc/model_tools.py
  hyperspy/misc/utils.py
  hyperspy/model.py
  hyperspy/models/edsmodel.py
  hyperspy/signal_tools.py
  hyperspy/tests/component/data/hs14_model.hspy
  hyperspy/tests/component/data/hs15_model.hspy
  hyperspy/tests/component/data/hs16_model.hspy
  hyperspy/tests/component/test_EELSarctan.py
  hyperspy/tests/component/test_arctan.py
  hyperspy/tests/component/test_backcompatibility.py
  hyperspy/tests/component/test_component_print_current.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_pes_voigt.py
  hyperspy/tests/component/test_voigt.py
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/drawing/test_plot_model.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
  hyperspy/tests/model/test_fitting.py
  hyperspy/tests/model/test_linear_model.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signals/test_cuda.py
  hyperspy/tests/signals/test_remove_background.py
  hyperspy/utils/markers.py
Labels: status: needs review, type: maintenance

#3155 Avoid fitting slowdown
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/models/model1d.py
  upcoming_changes/3155.bugfix.rst
Labels: status: needs review, type: bug-fix
