Repository hyperspy/hyperspy, pull requests merged in 2024-11, with the labels that each got.

#3030 PolygonROI
  doc/user_guide/region_of_interest.rst
  examples/region_of_interest/PolygonROI.py
  examples/region_of_interest/SpanROI.py
  examples/region_of_interest/SpanROI_interactive_sum.py
  examples/region_of_interest/combine_PolygonROI.py
  hyperspy/drawing/_widgets/circle.py
  hyperspy/drawing/_widgets/polygon.py
  hyperspy/drawing/_widgets/range.py
  hyperspy/drawing/widget.py
  hyperspy/drawing/widgets.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_widgets.py
  hyperspy/tests/test_import.py
  hyperspy/tests/utils/test_print_known_signal_types.py
  hyperspy/tests/utils/test_roi.py
  hyperspy/utils/roi.py
  upcoming_changes/3030.new.rst
Labels: type: new feature, status: waiting for author

#3456 Replace iterators by list in `hs.plot.plot_spectra` which fails with matplotlib 3.10
  hyperspy/drawing/utils.py
  upcoming_changes/3456.bugfix.rst
Labels: type: bug-fix, type: maintenance

#3457 Use custom version scheme in `setuptools_scm`
  doc/conf.py
  pyproject.toml
  setup.py
  upcoming_changes/3457.bugfix.rst
Labels: affects: documentation, status: needs review, type: bug-fix
