Repository hyperspy/hyperspy, pull requests merged in 2024-06, with the labels that each got.

#3384 Fix `mask` being replaced by the `blind_source_separation` method
  hyperspy/learn/mva.py
  hyperspy/tests/learn/test_bss.py
  hyperspy/tests/learn/test_decomposition.py
  upcoming_changes/3384.bugfix.rst
Labels: type: bug, status: needs review, type: bug-fix, release: next patch

#3379 Fix `add_poissonian_noise` and `add_gaussian_noise` changing data object
  .github/workflows/tests.yml
  hyperspy/signal.py
  hyperspy/tests/signals/test_2D.py
  pyproject.toml
  upcoming_changes/3379.bugfix.rst
Labels: type: bug, status: needs review, type: bug-fix, release: next patch

#3380 Improve documentation distributed scheduler
  doc/user_guide/big_data.rst
  doc/user_guide/signal2d.rst
  doc/user_guide/visualisation.rst
  hyperspy/io.py
  upcoming_changes/3380.enhancements.rst
Labels: type: enhancement, affects: documentation, status: needs review

#3366 Only import gui widget when the toolkit is enabled
  hyperspy/ui_registry.py
  upcoming_changes/3366.enhancements.rst
Labels: type: enhancement, status: needs review

#3355 Update residual line when model line is changed.
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/tests/drawing/test_plot_model1d.py
  upcoming_changes/3355.bugfix.rst
Labels: type: bug, type: bug-fix

#3388 Fix gradients in some expression based components
  hyperspy/_components/arctan.py
  hyperspy/_components/doniach.py
  hyperspy/_components/expression.py
  hyperspy/_components/heaviside.py
  hyperspy/_components/voigt.py
  hyperspy/tests/component/test_components.py
  hyperspy/tests/component/test_gaussian.py
  hyperspy/tests/component/test_heaviside.py
  hyperspy/tests/component/test_offset.py
  hyperspy/tests/component/test_polynomial.py
  hyperspy/tests/component/test_powerlaw.py
  hyperspy/tests/component/test_scalablefixedpattern.py
  upcoming_changes/3388.bugfix.rst
Labels: type: bug-fix
