Repository hyperspy/hyperspy, pull requests merged in 2024-08, with the labels that each got.

#3413 Fix loading polynomial saved with hyperspy <=2.1.1
  hyperspy/_components/expression.py
  hyperspy/_components/polynomial.py
  hyperspy/signal.py
  hyperspy/tests/component/data/hs211_model_polynomial_reload.hspy
  hyperspy/tests/component/test_backcompatibility.py
  upcoming_changes/3413.bugfix.rst
Labels: type: bug-fix

#3400 Add example: live FFT
  examples/region_of_interest/fast_fourier_transform_live.py
  pyproject.toml
  upcoming_changes/3400.doc.rst
Labels: status: WIP, release: next patch

#3409 Fix old version warning banner in the stable documentation
  doc/_static/switcher.json
  doc/conf.py
  upcoming_changes/3409.bugfix.rst
Labels: affects: documentation, status: needs review, type: bug-fix

#3421 Fix non-lazy map with processes scheduler
  hyperspy/signal.py
  hyperspy/tests/signals/test_map_method.py
  upcoming_changes/3421.bugfix.rst
  upcoming_changes/3421.enhancements.rst
Labels: status: needs review, type: bug-fix

#3418 Disable snap to axes for non uniform axis
  hyperspy/drawing/utils.py
  hyperspy/drawing/widget.py
  hyperspy/roi.py
  hyperspy/tests/drawing/test_plot_widgets.py
  upcoming_changes/3418.bugfix.rst
Labels: status: needs review, type: bug-fix

#3419 Add parameter to normalise spectra in `hs.plot.plot_spectra`
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/plot_signal1d/test_plot_spectra_normalise_cascade.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_spectra_normalise_heatmap.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_spectra_normalise_mosaic.png
  hyperspy/tests/drawing/plot_signal1d/test_plot_spectra_normalise_overlap.png
  hyperspy/tests/drawing/test_plot_signal1d.py
  upcoming_changes/3419.enhancements.rst
Labels: type: enhancement, status: needs review

#3410 Add support to convert to uniform axis in `interpolate_on_axis`
  .github/workflows/tests.yml
  hyperspy/axes.py
  hyperspy/signal.py
  hyperspy/tests/axes/test_data_axis.py
  hyperspy/tests/signals/test_interpolate_on_axis.py
  upcoming_changes/3410.bugfix.rst
  upcoming_changes/3410.enhancements.rst
Labels: type: enhancement, status: needs review, type: bug-fix

#3428 Silence unnecessary warnings when using non-uniform axis
  hyperspy/_signals/signal1d.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_1D_tools.py
  hyperspy/tests/signals/test_map_method.py
  upcoming_changes/3428.bugfix.rst
Labels: type: bug-fix, type: maintenance

#3420 Improve `hs.data.atomic_resolution_image`
  hyperspy/data/artificial_data.py
  hyperspy/tests/test_data.py
  upcoming_changes/3420.enhancements.rst
Labels: type: enhancement
