Repository hyperspy/hyperspy, pull requests merged in 2024-09, with the labels that each got.

#3426 Linear optimizer improvements
  doc/user_guide/model/fitting_model.rst
  hyperspy/docstrings/model.py
  hyperspy/model.py
  hyperspy/tests/model/test_fit_component.py
  hyperspy/tests/model/test_linear_model.py
  upcoming_changes/3426.api.rst
  upcoming_changes/3426.enhancements.rst
Labels: type: enhancement

#3435 Update `set_signal_type` docstring
  CHANGES.rst
  doc/user_guide/io.rst
  doc/user_guide/signal/signal_basics.rst
  doc/user_guide/visualisation.rst
  hyperspy/signal.py
  upcoming_changes/3435.doc.rst
Labels: affects: documentation, status: needs review

#3437 Fix horizontal plotting with ipympl 0.9.4/ipython 8.24
  hyperspy/drawing/mpl_he.py
  upcoming_changes/3437.bugfix.rst
Labels: type: bug-fix

#3438 Fix interactive normalise in `hs.plot.plot_spectra`
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_roi_map.py
  hyperspy/tests/drawing/test_plot_signal1d.py
Labels: type: enhancement

#3439 Add style parameter to `print_known_signal_types`
  doc/conf.py
  hyperspy/tests/utils/test_print_known_signal_types.py
  hyperspy/utils/__init__.py
  upcoming_changes/3439.enhancements.rst
Labels: type: enhancement

#3422 Various `get_histogram` fixes
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/docstrings/signal.py
  hyperspy/drawing/utils.py
  hyperspy/misc/hist_tools.py
  hyperspy/signal.py
  hyperspy/tests/misc/test_hist_tools.py
  upcoming_changes/3422.bugfix.rst
Labels: type: bug-fix

#3343 New Feature: Add sub-figure plotting
  examples/plotting/README.rst
  examples/plotting/ROI_insets.py
  examples/plotting/custom_figure_layout.py
  hyperspy/conftest.py
  hyperspy/defaults_parser.py
  hyperspy/drawing/figure.py
  hyperspy/drawing/image.py
  hyperspy/drawing/mpl_he.py
  hyperspy/drawing/mpl_hie.py
  hyperspy/drawing/mpl_hse.py
  hyperspy/drawing/utils.py
  hyperspy/signal.py
  hyperspy/tests/drawing/test_figure.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/drawing/test_plot_signal2d.py
  hyperspy/tests/drawing/test_plot_signal_tools.py
  upcoming_changes/3343.new.rst
Labels: type: new feature
