Repository hyperspy/hyperspy, pull requests merged in 2025-02, with the labels that each got.

#3476 Fix and improve `BaseModel.as_signal`
  .github/workflows/tests.yml
  .github/workflows/tests_extension.yml
  CHANGES.rst
  conda_environment.yml
  doc/user_guide/model/model_components.rst
  examples/simple_simulations/two_gaussians.py
  hyperspy/_components/doniach.py
  hyperspy/_components/expression.py
  hyperspy/_components/offset.py
  hyperspy/_components/power_law.py
  hyperspy/_components/scalable_fixed_pattern.py
  hyperspy/_components/split_voigt.py
  hyperspy/_components/voigt.py
  hyperspy/_signals/signal1d.py
  hyperspy/data/two_gaussians.py
  hyperspy/docstrings/parameters.py
  hyperspy/misc/array_tools.py
  hyperspy/model.py
  hyperspy/models/model1d.py
  hyperspy/tests/component/test_components2D.py
  hyperspy/tests/component/test_expression.py
  hyperspy/tests/component/test_gaussian.py
  hyperspy/tests/component/test_offset.py
  hyperspy/tests/component/test_polynomial.py
  hyperspy/tests/component/test_powerlaw.py
  hyperspy/tests/misc/test_array_tools.py
  hyperspy/tests/model/test_linear_model.py
  hyperspy/tests/model/test_model.py
  hyperspy/tests/signals/test_remove_background.py
  hyperspy/tests/utils/test_roi.py
  pyproject.toml
  upcoming_changes/3476.enhancements.rst
Labels: type: enhancement, type: bug-fix, run-extension-tests

#3468 Python 3.13
  .github/workflows/tests.yml
  azure-pipelines.yml
  conda_environment.yml
  hyperspy/events.py
  hyperspy/io.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  hyperspy/tests/signals/test_cuda.py
  pyproject.toml
  upcoming_changes/3468.maintenance.rst
Labels: status: needs review, type: maintenance

#3475 Remove unneeded replace for docstring `OPTIMIZE_ARG`
  hyperspy/_signals/common_signal1d.py
  hyperspy/_signals/common_signal2d.py
  hyperspy/signal.py
Labels: affects: documentation, status: needs review

#3482 Clean-up dependencies
  CHANGES.rst
  conda_environment.yml
  hyperspy/_signals/lazy.py
  pyproject.toml
  upcoming_changes/3482.maintenance.rst
Labels: type: maintenance

#3436 Add `remove_spikes` method
  doc/conf.py
  doc/user_guide/signal/generic_tools.rst
  doc/user_guide/signal1d.rst
  hyperspy/_signals/signal1d.py
  hyperspy/docstrings/signal1d.py
  hyperspy/external/scipy/__init__.py
  hyperspy/external/scipy/ndfilters.py
  hyperspy/learn/mva.py
  hyperspy/roi.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_cuda.py
  hyperspy/tests/signals/test_tools.py
  pyproject.toml
  upcoming_changes/3436.new.rst
Labels: type: enhancement, status: needs review

#3483 Fix plotting single spectra in `hs.plot.plot_spectra` with `style="mosaic"`
  hyperspy/drawing/utils.py
  hyperspy/tests/drawing/test_plot_signal1d.py
  upcoming_changes/3483.bugfix.rst
Labels: type: bug-fix, type: maintenance

#3485 `remove_spikes` typos
  doc/user_guide/signal/generic_tools.rst
  hyperspy/_signals/signal1d.py
  hyperspy/signal.py
Labels: type: typo

#3441 Remove baseline functionality using `pybaselines`
  .gitignore
  conda_environment.yml
  doc/conf.py
  doc/user_guide/images/signal_1d_remove_baseline.png
  doc/user_guide/signal1d.rst
  examples/processing/README.rst
  examples/processing/baseline_removal.py
  hyperspy/_signals/_signal1d_tool.py
  hyperspy/_signals/lazy.py
  hyperspy/_signals/signal1d.py
  hyperspy/docstrings/signal.py
  hyperspy/drawing/signal1d.py
  hyperspy/hyperspy_extension.yaml
  hyperspy/misc/utils.py
  hyperspy/signal.py
  hyperspy/tests/signals/test_remove_baseline.py
  hyperspy/ui_registry.py
  hyperspy/utils/baseline_removal_tool.py
  pyproject.toml
  upcoming_changes/3441.new.rst
Labels: status: needs review, type: new feature
